package com.sibirskyspeak.data

import com.sibirskyspeak.data.Card
import com.sibirskyspeak.data.CardType

// Generated by generate_concepts.py. Do not edit manually.

data class GrammarConcept(
    val id: String,
    val title: String,
    val lesson: String,
    val exampleRu: String,
    val exampleEn: String,
    val hint: String,
    val order: Int,
    val spine: Boolean = true,
    val cefrLevel: String,
    val prerequisites: List<String> = emptyList(),
    val interferesWith: List<String> = emptyList(),
    val family: String = id.substringBefore('_'),
    val stage: Int = 1
)

object GrammarConcepts {
    val GEN_CHUNK_POSSESSION = GrammarConcept(
        id = "GEN_CHUNK_POSSESSION",
        title = "Having: у меня есть",
        lesson = "Russian expresses possession as something existing 'by' a person. Learn the whole frame before producing genitive endings.",
        exampleRu = "У меня есть книга.",
        exampleEn = "I have a book.",
        hint = "Use у + person + есть.",
        order = 55,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "GEN",
        stage = 0
    )

    val GEN_CHUNK_ABSENCE = GrammarConcept(
        id = "GEN_CHUNK_ABSENCE",
        title = "Not having: у меня нет",
        lesson = "Absence uses the fixed frame у + person + нет. Treat the following form as part of the phrase for now.",
        exampleRu = "У меня нет времени.",
        exampleEn = "I have no time.",
        hint = "Use у + person + нет.",
        order = 56,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf("GEN_CHUNK_POSSESSION"),
        interferesWith = listOf(),
        family = "GEN",
        stage = 0
    )

    val PREP_CHUNK_LOCATION = GrammarConcept(
        id = "PREP_CHUNK_LOCATION",
        title = "Location chunks",
        lesson = "Learn common locations as whole phrases with в/на: в школе, на работе. The ending system comes later.",
        exampleRu = "Я в школе.",
        exampleEn = "I am at school.",
        hint = "Where? Use a learned в/на location chunk.",
        order = 65,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PREP",
        stage = 0
    )

    val DAT_CHUNK_EXPERIENCER = GrammarConcept(
        id = "DAT_CHUNK_EXPERIENCER",
        title = "Experiencer chunks",
        lesson = "Russian often puts the person experiencing a feeling in forms such as мне/тебе. Learn these high-frequency frames whole.",
        exampleRu = "Мне нравится музыка.",
        exampleEn = "I like music.",
        hint = "Use мне/тебе + experience.",
        order = 75,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "DAT",
        stage = 0
    )

    val INS_CHUNK_WITH = GrammarConcept(
        id = "INS_CHUNK_WITH",
        title = "With someone",
        lesson = "Learn с + person as a useful whole phrase. Productive instrumental endings unlock later.",
        exampleRu = "Я иду с другом.",
        exampleEn = "I am going with a friend.",
        hint = "Together with: с + learned form.",
        order = 85,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "INS",
        stage = 0
    )

    val GENDER = GrammarConcept(
        id = "GENDER",
        title = "Noun gender",
        lesson = "Every Russian noun is masculine, feminine, or neuter. You usually can tell from the ending: a consonant or -й is masculine, -а/-я is feminine, -о/-е is neuter. Gender matters because adjectives and past-tense verbs change their endings to match the noun.",
        exampleRu = "стол (masculine) · книга (feminine) · окно (neuter)",
        exampleEn = "table (masculine) · book (feminine) · window (neuter)",
        hint = "Ending → gender: consonant/-й = masculine, -а/-я = feminine, -о/-е = neuter.",
        order = 10,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "GENDER",
        stage = 1
    )

    val NOM_PL = GrammarConcept(
        id = "NOM_PL",
        title = "Making plurals",
        lesson = "To talk about more than one thing, most masculine and feminine nouns add -ы or -и, and most neuter nouns change -о/-е to -а/-я. This is the plural you use as the subject of a sentence.",
        exampleRu = "стол → столы · книга → книги · окно → окна",
        exampleEn = "table → tables · book → books · window → windows",
        hint = "Plural: usually -ы/-и; neuter -о/-е → -а/-я.",
        order = 30,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "NOM",
        stage = 1
    )

    val ACC = GrammarConcept(
        id = "ACC",
        title = "The accusative (direct object)",
        lesson = "The accusative marks the direct object — the thing the action happens to. Masculine inanimate and neuter nouns look the same as the dictionary form; feminine nouns change -а → -у and -я → -ю.",
        exampleRu = "Я читаю книгу.",
        exampleEn = "I'm reading a book. (книга → книгу)",
        hint = "Direct object → accusative. Feminine -а → -у, -я → -ю.",
        order = 50,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "ACC",
        stage = 1
    )

    val GEN = GrammarConcept(
        id = "GEN",
        title = "The genitive (\\, absence)",
        lesson = "The genitive shows possession or \\ something, and is used for absence (нет + genitive) and after words like без, из, у. Masculine/neuter nouns usually take -а/-я; feminine -а/-я become -ы/-и.",
        exampleRu = "У меня нет времени.",
        exampleEn = "I have no time. (время → времени)",
        hint = "\\ / нет / без / из / у → genitive.",
        order = 60,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "GEN",
        stage = 1
    )

    val PREP = GrammarConcept(
        id = "PREP",
        title = "The prepositional (location)",
        lesson = "The prepositional only appears after a preposition — mainly в/на for location (\\) and о for a topic (\\). Most nouns simply take the ending -е.",
        exampleRu = "Книга на столе.",
        exampleEn = "The book is on the table. (стол → столе)",
        hint = "After в/на (where) and о (about) → prepositional, usually -е.",
        order = 70,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PREP",
        stage = 1
    )

    val DAT = GrammarConcept(
        id = "DAT",
        title = "The dative (\\)",
        lesson = "The dative marks the recipient — the person something is given, said, or shown to. It also appears after к and по, and in age and \\ phrases. Masculine/neuter take -у/-ю; feminine take -е.",
        exampleRu = "Я пишу другу.",
        exampleEn = "I'm writing to a friend. (друг → другу)",
        hint = "Recipient \\, к, по, age → dative.",
        order = 80,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "DAT",
        stage = 1
    )

    val INS = GrammarConcept(
        id = "INS",
        title = "The instrumental (\\)",
        lesson = "The instrumental shows the means \\ which something is done, and follows с (\\). Masculine/neuter take -ом/-ем; feminine take -ой/-ей.",
        exampleRu = "Я пишу ручкой.",
        exampleEn = "I write with a pen. (ручка → ручкой)",
        hint = "Means \\, and с (together with) → instrumental.",
        order = 90,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "INS",
        stage = 1
    )

    val PAST = GrammarConcept(
        id = "PAST",
        title = "The past tense",
        lesson = "The Russian past tense is easy: drop -ть and add -л for a male subject, -ла for female, -ло for neuter, -ли for plural. It agrees with the subject's gender and number, not the person.",
        exampleRu = "Он читал. Она читала. Они читали.",
        exampleEn = "He read. She read. They read.",
        hint = "Past = stem + -л/-ла/-ло/-ли (agrees with subject gender/number).",
        order = 100,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PAST",
        stage = 1
    )

    val ADJ_AGREE = GrammarConcept(
        id = "ADJ_AGREE",
        title = "Adjective agreement",
        lesson = "Adjectives copy the gender and number of the noun they describe. The dictionary form is masculine (-ый/-ий); feminine ends -ая, neuter -ое, and plural -ые/-ие.",
        exampleRu = "новый дом · новая книга · новое окно · новые дома",
        exampleEn = "new house · new book · new window · new houses",
        hint = "Adjective matches its noun: -ый/-ий/-ой (masculine), -ая/-яя (feminine), -ое/-ее (neuter), -ые/-ие (plural).",
        order = 20,
        spine = false,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "ADJ",
        stage = 1
    )

    val PRESENT = GrammarConcept(
        id = "PRESENT",
        title = "The present tense",
        lesson = "Russian present tense uses six personal forms: я, ты, он/она/оно, мы, вы, они. The hard part is the stem: common verbs change consonants or vowels, so learn the full mini-paradigm instead of guessing from the infinitive.",
        exampleRu = "писать -> пишу, пишешь, пишет; любить -> люблю, любишь, любит",
        exampleEn = "to write -> I write, you write, he writes; to love -> I love, you love, he loves",
        hint = "Present: learn the stored stem pattern; watch mutations like писать -> пишу, любить -> люблю.",
        order = 40,
        spine = true,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PRESENT",
        stage = 1
    )

    val ASPECT = GrammarConcept(
        id = "ASPECT",
        title = "Verb aspect",
        lesson = "Most Russian verbs come in pairs. The imperfective describes an ongoing or repeated action (\\); the perfective describes a single completed action with a result (\\). Choose by whether the action reached its end.",
        exampleRu = "Я писал письмо. / Я написал письмо.",
        exampleEn = "I was writing a letter. / I wrote (finished) a letter.",
        hint = "Ongoing/repeated = imperfective; completed result = perfective.",
        order = 110,
        spine = false,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "ASPECT",
        stage = 1
    )

    val FUTURE = GrammarConcept(
        id = "FUTURE",
        title = "The future tense",
        lesson = "Russian has two futures. The imperfective future uses бу́ду, бу́дешь, бу́дет … plus the imperfective infinitive (ongoing/repeated). The perfective future is just the perfective verb conjugated like the present — it already means a single completed future action.",
        exampleRu = "Я бу́ду чита́ть. / Я прочита́ю кни́гу.",
        exampleEn = "I will be reading. / I will read (finish) the book.",
        hint = "Future: буду + imperfective inf, OR conjugated perfective.",
        order = 120,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "FUTURE",
        stage = 1
    )

    val IMPERATIVE = GrammarConcept(
        id = "IMPERATIVE",
        title = "Commands (imperative)",
        lesson = "To tell someone to do something, take the present-tense stem and add -й (after a vowel), -и (after a consonant, stressed), or -ь. Add -те for polite/plural. Imperfective invites; perfective asks for one result.",
        exampleRu = "Чита́й! Чита́йте! Напиши́те письмо́.",
        exampleEn = "Read! Read (pl.)! Write the letter.",
        hint = "Command: stem + -й/-и(+те). Perfective = one result.",
        order = 130,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "IMPERATIVE",
        stage = 1
    )

    val REFLEXIVE = GrammarConcept(
        id = "REFLEXIVE",
        title = "Reflexive verbs (-ся)",
        lesson = "Verbs ending in -ся/-сь turn the action back on the subject or make it intransitive: учи́ть (teach) → учи́ться (study), нача́ть (begin sth) → нача́ться (begin, of itself). The ending is -ся after a consonant, -сь after a vowel.",
        exampleRu = "Я учу́сь. Уро́к начина́ется.",
        exampleEn = "I study. The lesson begins.",
        hint = "-ся/-сь = action on oneself / intransitive.",
        order = 140,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "REFLEXIVE",
        stage = 1
    )

    val COMPARATIVE = GrammarConcept(
        id = "COMPARATIVE",
        title = "Comparing things",
        lesson = "For \\, most adjectives and adverbs add -ее (бы́стрый → быстре́е), with some irregulars (хоро́ший → лу́чше, большо́й → бо́льше). \\ is чем, or put the compared thing in the genitive.",
        exampleRu = "Э́та кни́га интере́снее. Москва́ бо́льше.",
        exampleEn = "This book is more interesting. Moscow is bigger.",
        hint = "More: adjective + -ее (лучше/больше). \\ = чем or genitive.",
        order = 150,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "COMPARATIVE",
        stage = 1
    )

    val MODAL = GrammarConcept(
        id = "MODAL",
        title = "Can, must, need (dative)",
        lesson = "\\ мо́жно, \\ на́до/ну́жно, \\ +\n             нельзя́ are used with the dative of the person and an infinitive. There is no \\ in the present.",
        exampleRu = "Мне на́до рабо́тать. Здесь мо́жно кури́ть?",
        exampleEn = "I need to work. May one smoke here?",
        hint = "надо/нужно/можно/нельзя + dative person + infinitive.",
        order = 160,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "MODAL",
        stage = 1
    )

    val MOTION = GrammarConcept(
        id = "MOTION",
        title = "Verbs of motion (go)",
        lesson = "Russian splits \\ by manner and direction. Use идти́/е́хать for one trip in one direction now; ходи́ть/е́здить for repeated, round, or general movement. идти́/ходи́ть = on foot, е́хать/е́здить = by vehicle.",
        exampleRu = "Я иду́ в шко́лу. Я ча́сто хожу́ в парк.",
        exampleEn = "I'm going to school (now). I often go to the park.",
        hint = "идти/ехать = one trip now; ходить/ездить = repeated/round.",
        order = 170,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "MOTION",
        stage = 1
    )

    val POSSESSIVE_SVOJ = GrammarConcept(
        id = "POSSESSIVE_SVOJ",
        title = "One's own (свой)",
        lesson = "свой means \\ and refers back to the subject of the clause. It agrees like мой. Use it instead of его/её/их when the owner is the subject, to avoid ambiguity.",
        exampleRu = "Он чита́ет свою́ кни́гу.",
        exampleEn = "He is reading his (own) book.",
        hint = "свой = belonging to the subject; agrees like мой.",
        order = 180,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "POSSESSIVE",
        stage = 1
    )

    val MOTION_PREFIX = GrammarConcept(
        id = "MOTION_PREFIX",
        title = "Prefixed motion verbs",
        lesson = "Prefixes add direction to motion verbs: при- (arrive), у- (leave), в-/во- (enter), вы- (exit), по- (set off). On идти-type stems they form aspect pairs (приходи́ть/прийти́).",
        exampleRu = "Он пришёл домо́й и ушёл сно́ва.",
        exampleEn = "He came home and left again.",
        hint = "при-=arrive, у-=leave, в-=enter, вы-=exit, по-=set off.",
        order = 190,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "MOTION",
        stage = 1
    )

    val CONDITIONAL = GrammarConcept(
        id = "CONDITIONAL",
        title = "Would / conditional (бы)",
        lesson = "The particle бы plus a past-tense verb expresses a hypothetical: \\. For \\, use е́сли бы … (past), … бы … (past) in both clauses.",
        exampleRu = "Я бы помо́г. Е́сли бы я знал, я бы сказа́л.",
        exampleEn = "I would help. If I had known, I would have said.",
        hint = "бы + past = \\. Если бы … , … бы …",
        order = 200,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "CONDITIONAL",
        stage = 1
    )

    val RELATIVE = GrammarConcept(
        id = "RELATIVE",
        title = "Which / who (который)",
        lesson = "кото́рый links clauses (\\). It agrees in gender and number with the noun it refers to, but takes its case from its role in its own clause.",
        exampleRu = "Кни́га, кото́рую я чита́ю, интере́сная.",
        exampleEn = "The book that I'm reading is interesting.",
        hint = "который: gender/number from antecedent, case from its own clause.",
        order = 210,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "RELATIVE",
        stage = 1
    )

    val SUPERLATIVE = GrammarConcept(
        id = "SUPERLATIVE",
        title = "The most (superlative)",
        lesson = "The most common superlative puts са́мый (agreeing like an adjective) before the adjective. Some forms also use -ейший/-айший.",
        exampleRu = "Э́то са́мый интере́сный го́род.",
        exampleEn = "This is the most interesting city.",
        hint = "самый + adjective = \\.",
        order = 220,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "SUPERLATIVE",
        stage = 1
    )

    val PURPOSE = GrammarConcept(
        id = "PURPOSE",
        title = "In order to (чтобы)",
        lesson = "что́бы expresses purpose. With the same subject, use чтобы + infinitive. With a different subject, use чтобы + past tense (the subjunctive use).",
        exampleRu = "Я чита́ю, что́бы учи́ться. Я хочу́, что́бы ты пришёл.",
        exampleEn = "I read in order to study. I want you to come.",
        hint = "чтобы + infinitive (same subj) / + past (different subj).",
        order = 230,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PURPOSE",
        stage = 1
    )

    val NUMERAL_CASE = GrammarConcept(
        id = "NUMERAL_CASE",
        title = "Numbers and nouns",
        lesson = "After numbers the noun changes: 1 → nominative; 2–4 → genitive singular; 5 and up → genitive plural. This also follows ско́лько and мно́го.",
        exampleRu = "одна́ кни́га, две кни́ги, пять книг",
        exampleEn = "one book, two books, five books",
        hint = "1 → nom; 2–4 → gen sg; 5+ → gen pl.",
        order = 240,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "NUMERAL",
        stage = 1
    )

    val SHORT_FORM_ADJ = GrammarConcept(
        id = "SHORT_FORM_ADJ",
        title = "Predicate short forms",
        lesson = "Many adjectives have a short form used only as the predicate (after an implied \\, never before a noun): drop the full ending and add nothing for masculine, -а for feminine, -о for neuter, -ы/-и for plural. You already know до́лжен this way. Short forms describe a temporary state or judgment; the full form (краси́вый, etc.) still names an inherent quality.",
        exampleRu = "Он рад. Она́ ра́да. Мы ра́ды.",
        exampleEn = "He is glad. She is glad. We are glad.",
        hint = "Predicate-only form: masculine (bare stem), feminine -а, neuter -о, plural -ы/-и.",
        order = 245,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "SHORT",
        stage = 1
    )

    val PARTICIPLE_ACTIVE = GrammarConcept(
        id = "PARTICIPLE_ACTIVE",
        title = "Active participles",
        lesson = "Active participles work like \\ adjectives. Present: stem + -ущ/-ющ/-ащ/-ящ + adjective endings; past: -вш-. They agree with their noun and replace a кото́рый clause where that noun is the subject.",
        exampleRu = "челове́к, чита́ющий кни́гу",
        exampleEn = "the person reading a book (who reads a book)",
        hint = "Active participle = \\; agrees like an adjective.",
        order = 250,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PARTICIPLE",
        stage = 1
    )

    val PARTICIPLE_PASSIVE = GrammarConcept(
        id = "PARTICIPLE_PASSIVE",
        title = "Passive participles",
        lesson = "Passive participles mean \\. Present: -ем/-им; past: -нн/-енн/-т. The short past form (-н, -на, -но, -ны) builds the perfect passive: «письмо́ напи́сано».",
        exampleRu = "кни́га, напи́санная им; письмо́ напи́сано",
        exampleEn = "the book written by him; the letter is written",
        hint = "Passive participle = \\; short form -н/-на/-но/-ны = result.",
        order = 260,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PARTICIPLE",
        stage = 1
    )

    val GERUND = GrammarConcept(
        id = "GERUND",
        title = "Verbal adverbs (gerunds)",
        lesson = "A gerund (деепричастие) describes a secondary action by the same subject. Imperfective: stem + -я (\\); perfective: -в/-вши (\\). It never changes form.",
        exampleRu = "Чита́я письмо́, он молча́л.",
        exampleEn = "Reading the letter, he was silent.",
        hint = "Gerund: -я (while doing) / -в (having done); invariable.",
        order = 270,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "GERUND",
        stage = 1
    )

    val PASSIVE = GrammarConcept(
        id = "PASSIVE",
        title = "Passive constructions",
        lesson = "Russian forms the passive two ways: with a reflexive imperfective verb (дом строи́тся — \\) or with a short passive participle for completed results (дом постро́ен). The agent, if named, goes in the instrumental.",
        exampleRu = "Дом стро́ится рабо́чими. Догово́р подпи́сан.",
        exampleEn = "The house is being built by workers. The treaty is signed.",
        hint = "Passive: -ся verb (process) or short participle (result); agent = instrumental.",
        order = 280,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PASSIVE",
        stage = 1
    )

    val REPORTED = GrammarConcept(
        id = "REPORTED",
        title = "Reported speech",
        lesson = "Russian keeps the original tense in reported speech (no backshift). Use что for statements, ли for yes/no questions, and the original question word otherwise.",
        exampleRu = "Он сказа́л, что рабо́тает. Я спроси́л, придёт ли он.",
        exampleEn = "He said (that) he works. I asked whether he would come.",
        hint = "Reported: что / ли / question word; tense doesn't shift.",
        order = 290,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "REPORTED",
        stage = 1
    )

    val COMPLEX_SYNTAX = GrammarConcept(
        id = "COMPLEX_SYNTAX",
        title = "Connecting ideas",
        lesson = "Cohesive C1 writing chains clauses with connectors: одна́ко (however), поэ́тому (therefore), несмотря́ на то что (despite the fact that), в то вре́мя как (whereas), благодаря́ тому́ что (thanks to). They let you subordinate and contrast precisely.",
        exampleRu = "Несмотря́ на то что бы́ло тру́дно, он успе́л.",
        exampleEn = "Despite the fact that it was hard, he made it in time.",
        hint = "однако / поэтому / несмотря на то что / в то время как.",
        order = 300,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "COMPLEX",
        stage = 1
    )

    val NOMINALIZATION = GrammarConcept(
        id = "NOMINALIZATION",
        title = "Nominal style",
        lesson = "Formal Russian prefers verbal nouns over verbs: реши́ть → приня́тие реше́ния (taking a decision), разви́ть → разви́тие. This dense nominal style dominates official and academic registers.",
        exampleRu = "приня́тие реше́ния заняло́ вре́мя",
        exampleEn = "taking the decision took time",
        hint = "Formal register nominalises verbs: решить → принятие решения.",
        order = 310,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "NOMINALIZATION",
        stage = 1
    )

    val ASPECT_NUANCE = GrammarConcept(
        id = "ASPECT_NUANCE",
        title = "Fine points of aspect",
        lesson = "Beyond completion, aspect carries nuance: the imperfective can deny a fact (Я не чита́л — \\), state a general fact, or soften; the perfective stresses result and single occurrence. Negated commands usually take the imperfective.",
        exampleRu = "Не чита́й э́то! / Прочита́й э́то!",
        exampleEn = "Don't read this! / Read this (through)!",
        hint = "Imperfective: process/fact/negated commands; perfective: single result.",
        order = 320,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "ASPECT",
        stage = 1
    )

    val REGISTER = GrammarConcept(
        id = "REGISTER",
        title = "Register and style",
        lesson = "C1 control means matching register: neutral vs. bookish/official (данный = \\, осуществля́ть = \\, в связи́ с = \\ +\n            ) vs. colloquial. Word choice signals formality as much as grammar.",
        exampleRu = "в связи́ с да́нным реше́нием",
        exampleEn = "in connection with this decision (formal)",
        hint = "Match register: officialese (данный, осуществлять, в связи с) vs. neutral.",
        order = 330,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "REGISTER",
        stage = 1
    )

    val IDIOM = GrammarConcept(
        id = "IDIOM",
        title = "Set phrases and idiom",
        lesson = "Fluent Russian relies on fixed collocations and idioms whose meaning isn't literal: име́ть в виду́ (to mean), приня́ть во внима́ние (to take into account), име́ть значе́ние (to matter). Learn them as whole units.",
        exampleRu = "Я име́ю в виду́ друго́е.",
        exampleEn = "I mean something else.",
        hint = "Learn set phrases whole: иметь в виду, принять во внимание.",
        order = 340,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "IDIOM",
        stage = 1
    )

    val DISCOURSE_PARTICLES = GrammarConcept(
        id = "DISCOURSE_PARTICLES",
        title = "Hedging and reported stance",
        lesson = "Near-native Russian marks the speaker's distance from a quoted claim with reporting particles: мол and де́скать flag casual reported speech (\\), я́кобы signals the claim may be false (\\), and вро́де бы softens a statement (\\). None of these change the sentence's grammar — they only signal the speaker's stance toward it.",
        exampleRu = "Он сказа́л, мол, всё гото́во, но э́то я́кобы непра́вда.",
        exampleEn = "He said - so he claims - everything's ready, but that's allegedly not true.",
        hint = "мол/дескать = casual reported speech; якобы = doubted claim; вроде бы = soft hedge.",
        order = 350,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "DISCOURSE",
        stage = 1
    )

    val EMPHATIC_PARTICLES = GrammarConcept(
        id = "EMPHATIC_PARTICLES",
        title = "Emphasis and contrast particles",
        lesson = "A small set of particles carry pure emphasis with no dictionary translation of their own: ведь appeals to something the listener should already accept (\\), всё-та́ки signals a stubborn contrast (\\",
        exampleRu = "Он ведь зна́л об э́том, но всё-та́ки не сказа́л ни сло́ва.",
        exampleEn = "He knew about it, after all, but still didn't say a word.",
        hint = "ведь = appeals to shared knowledge; всё-таки = despite that; уж = indeed; лишь = only.",
        order = 360,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "EMPHATIC",
        stage = 1
    )

    val BOOKISH_SUBORDINATION = GrammarConcept(
        id = "BOOKISH_SUBORDINATION",
        title = "Literary connectors",
        lesson = "Formal and literary Russian has its own tier of subordinators above the C1 set: и́бо (\\, explains a cause), да́бы (archaic \\ +\n            ), поско́льку (\\",
        exampleRu = "Он не отве́тил, поско́льку не был уве́рен, и́бо вопро́с был сло́жным.",
        exampleEn = "He didn't answer, since he wasn't sure, for the question was complex.",
        hint = "ибо = for; дабы = in order that (archaic); поскольку = insofar as; вследствие того что = owing to.",
        order = 370,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "BOOKISH",
        stage = 1
    )

    val INVERSION_EMPHASIS = GrammarConcept(
        id = "INVERSION_EMPHASIS",
        title = "Emphatic word order",
        lesson = "Russian word order is freer than English, and near-native speakers use that freedom deliberately: fronting a word with и́менно marks it as the precise focus (\\",
        exampleRu = "И́менно он реши́л вопро́с; она́, в свою́ о́чередь, начала́ но́вый прое́кт.",
        exampleEn = "He specifically was the one who solved it; she, in turn, started a new project.",
        hint = "именно = precisely this one; недаром = no accident; тем не менее = nonetheless; в свою очередь = in turn.",
        order = 380,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "INVERSION",
        stage = 1
    )

    val SUBJUNCTIVE_NUANCE = GrammarConcept(
        id = "SUBJUNCTIVE_NUANCE",
        title = "Deeper hypotheticals",
        lesson = "Beyond the B1 бы conditional, C2 control includes concessive бы chains: что бы ни / как бы ни + past tense (\\), е́сли бы не (\\) for a counterfactual condition, and хотя́ бы (\\) for a minimal concession.",
        exampleRu = "Что бы ни случи́лось, е́сли бы не твоя́ по́мощь, я бы не спра́вился.",
        exampleEn = "Whatever happened, if not for your help, I wouldn't have managed.",
        hint = "что/как бы ни = no matter what/how; если бы не = if not for; хотя бы = at least.",
        order = 390,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "SUBJUNCTIVE",
        stage = 1
    )

    val QUESTIONS = GrammarConcept(
        id = "QUESTIONS",
        title = "Question formation",
        lesson = "This stage develops question formation as a reusable contrast in connected Russian.",
        exampleRu = "Question formation",
        exampleEn = "Question formation",
        hint = "Question formation",
        order = 25,
        spine = false,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "QUESTIONS",
        stage = 1
    )

    val CONNECTORS_A_NO = GrammarConcept(
        id = "CONNECTORS_A_NO",
        title = "And, but, and contrast: и/а/но",
        lesson = "This stage develops and, but, and contrast: и/а/но as a reusable contrast in connected Russian.",
        exampleRu = "And, but, and contrast: и/а/но",
        exampleEn = "And, but, and contrast: и/а/но",
        hint = "And, but, and contrast: и/а/но",
        order = 35,
        spine = false,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "CONNECTORS",
        stage = 1
    )

    val CARDINALS = GrammarConcept(
        id = "CARDINALS",
        title = "Cardinal numbers 0–100",
        lesson = "This stage develops cardinal numbers 0–100 as a reusable contrast in connected Russian.",
        exampleRu = "Cardinal numbers 0–100",
        exampleEn = "Cardinal numbers 0–100",
        hint = "Cardinal numbers 0–100",
        order = 45,
        spine = false,
        cefrLevel = "A1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "NUMERALS",
        stage = 1
    )

    val TIME_TELLING = GrammarConcept(
        id = "TIME_TELLING",
        title = "Telling time",
        lesson = "This stage develops telling time as a reusable contrast in connected Russian.",
        exampleRu = "Telling time",
        exampleEn = "Telling time",
        hint = "Telling time",
        order = 115,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "TIME",
        stage = 1
    )

    val ORDINALS_DATES = GrammarConcept(
        id = "ORDINALS_DATES",
        title = "Ordinals and dates",
        lesson = "This stage develops ordinals and dates as a reusable contrast in connected Russian.",
        exampleRu = "Ordinals and dates",
        exampleEn = "Ordinals and dates",
        hint = "Ordinals and dates",
        order = 125,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf("CARDINALS"),
        interferesWith = listOf(),
        family = "NUMERALS",
        stage = 2
    )

    val NUMERAL_GOV_234 = GrammarConcept(
        id = "NUMERAL_GOV_234",
        title = "Two, three, four + genitive singular",
        lesson = "This stage develops two, three, four + genitive singular as a reusable contrast in connected Russian.",
        exampleRu = "Two, three, four + genitive singular",
        exampleEn = "Two, three, four + genitive singular",
        hint = "Two, three, four + genitive singular",
        order = 185,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("ORDINALS_DATES"),
        interferesWith = listOf(),
        family = "NUMERALS",
        stage = 3
    )

    val NUMERAL_GOV_5 = GrammarConcept(
        id = "NUMERAL_GOV_5",
        title = "Five and above + genitive plural",
        lesson = "This stage develops five and above + genitive plural as a reusable contrast in connected Russian.",
        exampleRu = "Five and above + genitive plural",
        exampleEn = "Five and above + genitive plural",
        hint = "Five and above + genitive plural",
        order = 195,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("NUMERAL_GOV_234"),
        interferesWith = listOf(),
        family = "NUMERALS",
        stage = 4
    )

    val ASPECT_PAST = GrammarConcept(
        id = "ASPECT_PAST",
        title = "Aspect in the past",
        lesson = "This stage develops aspect in the past as a reusable contrast in connected Russian.",
        exampleRu = "Aspect in the past",
        exampleEn = "Aspect in the past",
        hint = "Aspect in the past",
        order = 105,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf("ASPECT"),
        interferesWith = listOf("ASPECT_FUTURE", "ASPECT_INFINITIVE", "ASPECT_IMPERATIVE", "ASPECT_NEGATION"),
        family = "ASPECT",
        stage = 2
    )

    val ASPECT_FUTURE = GrammarConcept(
        id = "ASPECT_FUTURE",
        title = "Aspect in the future",
        lesson = "This stage develops aspect in the future as a reusable contrast in connected Russian.",
        exampleRu = "Aspect in the future",
        exampleEn = "Aspect in the future",
        hint = "Aspect in the future",
        order = 135,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf("ASPECT_PAST"),
        interferesWith = listOf("ASPECT_PAST", "ASPECT_INFINITIVE", "ASPECT_IMPERATIVE", "ASPECT_NEGATION"),
        family = "ASPECT",
        stage = 3
    )

    val ASPECT_INFINITIVE = GrammarConcept(
        id = "ASPECT_INFINITIVE",
        title = "Aspect after modals and phase verbs",
        lesson = "This stage develops aspect after modals and phase verbs as a reusable contrast in connected Russian.",
        exampleRu = "Aspect after modals and phase verbs",
        exampleEn = "Aspect after modals and phase verbs",
        hint = "Aspect after modals and phase verbs",
        order = 175,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("ASPECT_FUTURE"),
        interferesWith = listOf("ASPECT_PAST", "ASPECT_FUTURE", "ASPECT_IMPERATIVE", "ASPECT_NEGATION"),
        family = "ASPECT",
        stage = 4
    )

    val ASPECT_IMPERATIVE = GrammarConcept(
        id = "ASPECT_IMPERATIVE",
        title = "Aspect in commands",
        lesson = "This stage develops aspect in commands as a reusable contrast in connected Russian.",
        exampleRu = "Aspect in commands",
        exampleEn = "Aspect in commands",
        hint = "Aspect in commands",
        order = 205,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("ASPECT_INFINITIVE"),
        interferesWith = listOf("ASPECT_PAST", "ASPECT_FUTURE", "ASPECT_INFINITIVE", "ASPECT_NEGATION"),
        family = "ASPECT",
        stage = 5
    )

    val ASPECT_NEGATION = GrammarConcept(
        id = "ASPECT_NEGATION",
        title = "Aspect under negation",
        lesson = "This stage develops aspect under negation as a reusable contrast in connected Russian.",
        exampleRu = "Aspect under negation",
        exampleEn = "Aspect under negation",
        hint = "Aspect under negation",
        order = 235,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("ASPECT_IMPERATIVE"),
        interferesWith = listOf("ASPECT_PAST", "ASPECT_FUTURE", "ASPECT_INFINITIVE", "ASPECT_IMPERATIVE"),
        family = "ASPECT",
        stage = 6
    )

    val MOTION_UNIDIRECTIONAL = GrammarConcept(
        id = "MOTION_UNIDIRECTIONAL",
        title = "идти/ехать: motion in one direction",
        lesson = "This stage develops идти/ехать: motion in one direction as a reusable contrast in connected Russian.",
        exampleRu = "идти/ехать: motion in one direction",
        exampleEn = "идти/ехать: motion in one direction",
        hint = "идти/ехать: motion in one direction",
        order = 145,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf(),
        interferesWith = listOf("MOTION_MULTIDIRECTIONAL", "MOTION_CARRY", "MOTION_TRANSPORT"),
        family = "MOTION",
        stage = 1
    )

    val MOTION_MULTIDIRECTIONAL = GrammarConcept(
        id = "MOTION_MULTIDIRECTIONAL",
        title = "ходить/ездить: habitual and round-trip motion",
        lesson = "This stage develops ходить/ездить: habitual and round-trip motion as a reusable contrast in connected Russian.",
        exampleRu = "ходить/ездить: habitual and round-trip motion",
        exampleEn = "ходить/ездить: habitual and round-trip motion",
        hint = "ходить/ездить: habitual and round-trip motion",
        order = 165,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("MOTION_UNIDIRECTIONAL"),
        interferesWith = listOf("MOTION_UNIDIRECTIONAL", "MOTION_CARRY", "MOTION_TRANSPORT"),
        family = "MOTION",
        stage = 2
    )

    val MOTION_CARRY = GrammarConcept(
        id = "MOTION_CARRY",
        title = "Carrying and leading motion verbs",
        lesson = "This stage develops carrying and leading motion verbs as a reusable contrast in connected Russian.",
        exampleRu = "Carrying and leading motion verbs",
        exampleEn = "Carrying and leading motion verbs",
        hint = "Carrying and leading motion verbs",
        order = 215,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("MOTION_MULTIDIRECTIONAL"),
        interferesWith = listOf("MOTION_UNIDIRECTIONAL", "MOTION_MULTIDIRECTIONAL", "MOTION_TRANSPORT"),
        family = "MOTION",
        stage = 3
    )

    val MOTION_TRANSPORT = GrammarConcept(
        id = "MOTION_TRANSPORT",
        title = "Choosing motion by transport and context",
        lesson = "This stage develops choosing motion by transport and context as a reusable contrast in connected Russian.",
        exampleRu = "Choosing motion by transport and context",
        exampleEn = "Choosing motion by transport and context",
        hint = "Choosing motion by transport and context",
        order = 225,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("MOTION_CARRY"),
        interferesWith = listOf("MOTION_UNIDIRECTIONAL", "MOTION_MULTIDIRECTIONAL", "MOTION_CARRY"),
        family = "MOTION",
        stage = 4
    )

    val MOTION_PREFIX_ARRIVE_LEAVE = GrammarConcept(
        id = "MOTION_PREFIX_ARRIVE_LEAVE",
        title = "Motion prefixes при-/у-",
        lesson = "This stage develops motion prefixes при-/у- as a reusable contrast in connected Russian.",
        exampleRu = "Motion prefixes при-/у-",
        exampleEn = "Motion prefixes при-/у-",
        hint = "Motion prefixes при-/у-",
        order = 245,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf("MOTION_PREFIX_ENTER_EXIT", "MOTION_PREFIX_APPROACH", "MOTION_PREFIX_CROSS_PASS"),
        family = "MOTION_PREFIX",
        stage = 1
    )

    val MOTION_PREFIX_ENTER_EXIT = GrammarConcept(
        id = "MOTION_PREFIX_ENTER_EXIT",
        title = "Motion prefixes в-/вы-",
        lesson = "This stage develops motion prefixes в-/вы- as a reusable contrast in connected Russian.",
        exampleRu = "Motion prefixes в-/вы-",
        exampleEn = "Motion prefixes в-/вы-",
        hint = "Motion prefixes в-/вы-",
        order = 255,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("MOTION_PREFIX_ARRIVE_LEAVE"),
        interferesWith = listOf("MOTION_PREFIX_ARRIVE_LEAVE", "MOTION_PREFIX_APPROACH", "MOTION_PREFIX_CROSS_PASS"),
        family = "MOTION_PREFIX",
        stage = 2
    )

    val MOTION_PREFIX_APPROACH = GrammarConcept(
        id = "MOTION_PREFIX_APPROACH",
        title = "Motion prefixes под-/от-/до-",
        lesson = "This stage develops motion prefixes под-/от-/до- as a reusable contrast in connected Russian.",
        exampleRu = "Motion prefixes под-/от-/до-",
        exampleEn = "Motion prefixes под-/от-/до-",
        hint = "Motion prefixes под-/от-/до-",
        order = 265,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("MOTION_PREFIX_ENTER_EXIT"),
        interferesWith = listOf("MOTION_PREFIX_ARRIVE_LEAVE", "MOTION_PREFIX_ENTER_EXIT", "MOTION_PREFIX_CROSS_PASS"),
        family = "MOTION_PREFIX",
        stage = 3
    )

    val MOTION_PREFIX_CROSS_PASS = GrammarConcept(
        id = "MOTION_PREFIX_CROSS_PASS",
        title = "Motion prefixes за-/пере-/про-",
        lesson = "This stage develops motion prefixes за-/пере-/про- as a reusable contrast in connected Russian.",
        exampleRu = "Motion prefixes за-/пере-/про-",
        exampleEn = "Motion prefixes за-/пере-/про-",
        hint = "Motion prefixes за-/пере-/про-",
        order = 275,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("MOTION_PREFIX_APPROACH"),
        interferesWith = listOf("MOTION_PREFIX_ARRIVE_LEAVE", "MOTION_PREFIX_ENTER_EXIT", "MOTION_PREFIX_APPROACH"),
        family = "MOTION_PREFIX",
        stage = 4
    )

    val GEN_PL = GrammarConcept(
        id = "GEN_PL",
        title = "Genitive plural",
        lesson = "This stage develops genitive plural as a reusable contrast in connected Russian.",
        exampleRu = "Genitive plural",
        exampleEn = "Genitive plural",
        hint = "Genitive plural",
        order = 155,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf("DAT_PL", "INS_PL", "PREP_PL"),
        family = "CASE_PLURAL",
        stage = 1
    )

    val DAT_PL = GrammarConcept(
        id = "DAT_PL",
        title = "Dative plural",
        lesson = "This stage develops dative plural as a reusable contrast in connected Russian.",
        exampleRu = "Dative plural",
        exampleEn = "Dative plural",
        hint = "Dative plural",
        order = 175,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("GEN_PL"),
        interferesWith = listOf("GEN_PL", "INS_PL", "PREP_PL"),
        family = "CASE_PLURAL",
        stage = 2
    )

    val INS_PL = GrammarConcept(
        id = "INS_PL",
        title = "Instrumental plural",
        lesson = "This stage develops instrumental plural as a reusable contrast in connected Russian.",
        exampleRu = "Instrumental plural",
        exampleEn = "Instrumental plural",
        hint = "Instrumental plural",
        order = 195,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("DAT_PL"),
        interferesWith = listOf("GEN_PL", "DAT_PL", "PREP_PL"),
        family = "CASE_PLURAL",
        stage = 3
    )

    val PREP_PL = GrammarConcept(
        id = "PREP_PL",
        title = "Prepositional plural",
        lesson = "This stage develops prepositional plural as a reusable contrast in connected Russian.",
        exampleRu = "Prepositional plural",
        exampleEn = "Prepositional plural",
        hint = "Prepositional plural",
        order = 215,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("INS_PL"),
        interferesWith = listOf("GEN_PL", "DAT_PL", "INS_PL"),
        family = "CASE_PLURAL",
        stage = 4
    )

    val GOV_INTEREST_INS = GrammarConcept(
        id = "GOV_INTEREST_INS",
        title = "интересоваться/заниматься + instrumental",
        lesson = "This stage develops интересоваться/заниматься + instrumental as a reusable contrast in connected Russian.",
        exampleRu = "интересоваться/заниматься + instrumental",
        exampleEn = "интересоваться/заниматься + instrumental",
        hint = "интересоваться/заниматься + instrumental",
        order = 185,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf("GOV_FEAR_GEN", "GOV_HELP_DAT", "GOV_WAIT_GEN_ACC", "GOV_DEPEND_ON"),
        family = "GOVERNMENT",
        stage = 1
    )

    val GOV_FEAR_GEN = GrammarConcept(
        id = "GOV_FEAR_GEN",
        title = "бояться + genitive",
        lesson = "This stage develops бояться + genitive as a reusable contrast in connected Russian.",
        exampleRu = "бояться + genitive",
        exampleEn = "бояться + genitive",
        hint = "бояться + genitive",
        order = 205,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("GOV_INTEREST_INS"),
        interferesWith = listOf("GOV_INTEREST_INS", "GOV_HELP_DAT", "GOV_WAIT_GEN_ACC", "GOV_DEPEND_ON"),
        family = "GOVERNMENT",
        stage = 2
    )

    val GOV_HELP_DAT = GrammarConcept(
        id = "GOV_HELP_DAT",
        title = "помогать + dative",
        lesson = "This stage develops помогать + dative as a reusable contrast in connected Russian.",
        exampleRu = "помогать + dative",
        exampleEn = "помогать + dative",
        hint = "помогать + dative",
        order = 225,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("GOV_FEAR_GEN"),
        interferesWith = listOf("GOV_INTEREST_INS", "GOV_FEAR_GEN", "GOV_WAIT_GEN_ACC", "GOV_DEPEND_ON"),
        family = "GOVERNMENT",
        stage = 3
    )

    val GOV_WAIT_GEN_ACC = GrammarConcept(
        id = "GOV_WAIT_GEN_ACC",
        title = "ждать + genitive or accusative",
        lesson = "This stage develops ждать + genitive or accusative as a reusable contrast in connected Russian.",
        exampleRu = "ждать + genitive or accusative",
        exampleEn = "ждать + genitive or accusative",
        hint = "ждать + genitive or accusative",
        order = 245,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("GOV_HELP_DAT"),
        interferesWith = listOf("GOV_INTEREST_INS", "GOV_FEAR_GEN", "GOV_HELP_DAT", "GOV_DEPEND_ON"),
        family = "GOVERNMENT",
        stage = 4
    )

    val GOV_DEPEND_ON = GrammarConcept(
        id = "GOV_DEPEND_ON",
        title = "зависеть от + genitive",
        lesson = "This stage develops зависеть от + genitive as a reusable contrast in connected Russian.",
        exampleRu = "зависеть от + genitive",
        exampleEn = "зависеть от + genitive",
        hint = "зависеть от + genitive",
        order = 265,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("GOV_WAIT_GEN_ACC"),
        interferesWith = listOf("GOV_INTEREST_INS", "GOV_FEAR_GEN", "GOV_HELP_DAT", "GOV_WAIT_GEN_ACC"),
        family = "GOVERNMENT",
        stage = 5
    )

    val GOV_MANAGE_INS = GrammarConcept(
        id = "GOV_MANAGE_INS",
        title = "управлять + instrumental",
        lesson = "This stage develops управлять + instrumental as a reusable contrast in connected Russian.",
        exampleRu = "управлять + instrumental",
        exampleEn = "управлять + instrumental",
        hint = "управлять + instrumental",
        order = 285,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("GOV_DEPEND_ON"),
        interferesWith = listOf("GOV_INTEREST_INS", "GOV_FEAR_GEN", "GOV_HELP_DAT", "GOV_WAIT_GEN_ACC"),
        family = "GOVERNMENT",
        stage = 6
    )

    val GOV_USE_INS = GrammarConcept(
        id = "GOV_USE_INS",
        title = "пользоваться + instrumental",
        lesson = "This stage develops пользоваться + instrumental as a reusable contrast in connected Russian.",
        exampleRu = "пользоваться + instrumental",
        exampleEn = "пользоваться + instrumental",
        hint = "пользоваться + instrumental",
        order = 305,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("GOV_MANAGE_INS"),
        interferesWith = listOf("GOV_INTEREST_INS", "GOV_FEAR_GEN", "GOV_HELP_DAT", "GOV_WAIT_GEN_ACC"),
        family = "GOVERNMENT",
        stage = 7
    )

    val GOV_CONGRAT_DAT = GrammarConcept(
        id = "GOV_CONGRAT_DAT",
        title = "благодарить + accusative; благодарен + dative",
        lesson = "This stage develops благодарить + accusative; благодарен + dative as a reusable contrast in connected Russian.",
        exampleRu = "благодарить + accusative; благодарен + dative",
        exampleEn = "благодарить + accusative; благодарен + dative",
        hint = "благодарить + accusative; благодарен + dative",
        order = 325,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("GOV_USE_INS"),
        interferesWith = listOf("GOV_INTEREST_INS", "GOV_FEAR_GEN", "GOV_HELP_DAT", "GOV_WAIT_GEN_ACC"),
        family = "GOVERNMENT",
        stage = 8
    )

    val POSITION_STATE = GrammarConcept(
        id = "POSITION_STATE",
        title = "Standing, lying, and hanging",
        lesson = "This stage develops standing, lying, and hanging as a reusable contrast in connected Russian.",
        exampleRu = "Standing, lying, and hanging",
        exampleEn = "Standing, lying, and hanging",
        hint = "Standing, lying, and hanging",
        order = 235,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "POSITION",
        stage = 1
    )

    val POSITION_CAUSED = GrammarConcept(
        id = "POSITION_CAUSED",
        title = "Putting, laying, and hanging",
        lesson = "This stage develops putting, laying, and hanging as a reusable contrast in connected Russian.",
        exampleRu = "Putting, laying, and hanging",
        exampleEn = "Putting, laying, and hanging",
        hint = "Putting, laying, and hanging",
        order = 255,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("POSITION_STATE"),
        interferesWith = listOf(),
        family = "POSITION",
        stage = 2
    )

    val TIME_WEEK_ACC = GrammarConcept(
        id = "TIME_WEEK_ACC",
        title = "Days and recurrence with в + accusative",
        lesson = "This stage develops days and recurrence with в + accusative as a reusable contrast in connected Russian.",
        exampleRu = "Days and recurrence with в + accusative",
        exampleEn = "Days and recurrence with в + accusative",
        hint = "Days and recurrence with в + accusative",
        order = 145,
        spine = false,
        cefrLevel = "A2",
        prerequisites = listOf("TIME_TELLING"),
        interferesWith = listOf(),
        family = "TIME",
        stage = 2
    )

    val TIME_MONTH_PREP = GrammarConcept(
        id = "TIME_MONTH_PREP",
        title = "Months and years with в + prepositional",
        lesson = "This stage develops months and years with в + prepositional as a reusable contrast in connected Russian.",
        exampleRu = "Months and years with в + prepositional",
        exampleEn = "Months and years with в + prepositional",
        hint = "Months and years with в + prepositional",
        order = 165,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("TIME_WEEK_ACC"),
        interferesWith = listOf(),
        family = "TIME",
        stage = 3
    )

    val TIME_DURATION = GrammarConcept(
        id = "TIME_DURATION",
        title = "Duration: назад and в течение",
        lesson = "This stage develops duration: назад and в течение as a reusable contrast in connected Russian.",
        exampleRu = "Duration: назад and в течение",
        exampleEn = "Duration: назад and в течение",
        hint = "Duration: назад and в течение",
        order = 205,
        spine = false,
        cefrLevel = "B1",
        prerequisites = listOf("TIME_MONTH_PREP"),
        interferesWith = listOf(),
        family = "TIME",
        stage = 4
    )

    val TIME_DEADLINE = GrammarConcept(
        id = "TIME_DEADLINE",
        title = "Deadline and completion: к, за, на",
        lesson = "This stage develops deadline and completion: к, за, на as a reusable contrast in connected Russian.",
        exampleRu = "Deadline and completion: к, за, на",
        exampleEn = "Deadline and completion: к, за, на",
        hint = "Deadline and completion: к, за, на",
        order = 245,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("TIME_DURATION"),
        interferesWith = listOf(),
        family = "TIME",
        stage = 5
    )

    val PREFIX_SEMANTICS = GrammarConcept(
        id = "PREFIX_SEMANTICS",
        title = "Productive verb-prefix meanings",
        lesson = "This stage develops productive verb-prefix meanings as a reusable contrast in connected Russian.",
        exampleRu = "Productive verb-prefix meanings",
        exampleEn = "Productive verb-prefix meanings",
        hint = "Productive verb-prefix meanings",
        order = 285,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "WORD_FORMATION",
        stage = 1
    )

    val SUFFIX_OST = GrammarConcept(
        id = "SUFFIX_OST",
        title = "Abstract nouns in -ость",
        lesson = "This stage develops abstract nouns in -ость as a reusable contrast in connected Russian.",
        exampleRu = "Abstract nouns in -ость",
        exampleEn = "Abstract nouns in -ость",
        hint = "Abstract nouns in -ость",
        order = 305,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("PREFIX_SEMANTICS"),
        interferesWith = listOf(),
        family = "WORD_FORMATION",
        stage = 2
    )

    val SUFFIX_ENIE = GrammarConcept(
        id = "SUFFIX_ENIE",
        title = "Event nouns in -ение",
        lesson = "This stage develops event nouns in -ение as a reusable contrast in connected Russian.",
        exampleRu = "Event nouns in -ение",
        exampleEn = "Event nouns in -ение",
        hint = "Event nouns in -ение",
        order = 325,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("SUFFIX_OST"),
        interferesWith = listOf(),
        family = "WORD_FORMATION",
        stage = 3
    )

    val AGENT_SUFFIXES = GrammarConcept(
        id = "AGENT_SUFFIXES",
        title = "People and roles: -тель/-ник",
        lesson = "This stage develops people and roles: -тель/-ник as a reusable contrast in connected Russian.",
        exampleRu = "People and roles: -тель/-ник",
        exampleEn = "People and roles: -тель/-ник",
        hint = "People and roles: -тель/-ник",
        order = 345,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("SUFFIX_ENIE"),
        interferesWith = listOf(),
        family = "WORD_FORMATION",
        stage = 4
    )

    val DIMINUTIVES = GrammarConcept(
        id = "DIMINUTIVES",
        title = "Diminutives and stance",
        lesson = "This stage develops diminutives and stance as a reusable contrast in connected Russian.",
        exampleRu = "Diminutives and stance",
        exampleEn = "Diminutives and stance",
        hint = "Diminutives and stance",
        order = 365,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("AGENT_SUFFIXES"),
        interferesWith = listOf(),
        family = "WORD_FORMATION",
        stage = 5
    )

    val ASPECT_PREFIXATION = GrammarConcept(
        id = "ASPECT_PREFIXATION",
        title = "Building aspect through prefixation",
        lesson = "This stage develops building aspect through prefixation as a reusable contrast in connected Russian.",
        exampleRu = "Building aspect through prefixation",
        exampleEn = "Building aspect through prefixation",
        hint = "Building aspect through prefixation",
        order = 385,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("DIMINUTIVES"),
        interferesWith = listOf(),
        family = "WORD_FORMATION",
        stage = 6
    )

    val INDEFINITE_TO = GrammarConcept(
        id = "INDEFINITE_TO",
        title = "Specific unknowns with -то",
        lesson = "This stage develops specific unknowns with -то as a reusable contrast in connected Russian.",
        exampleRu = "Specific unknowns with -то",
        exampleEn = "Specific unknowns with -то",
        hint = "Specific unknowns with -то",
        order = 275,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "INDEFINITES",
        stage = 1
    )

    val INDEFINITE_NIBUD = GrammarConcept(
        id = "INDEFINITE_NIBUD",
        title = "Open-choice unknowns with -нибудь",
        lesson = "This stage develops open-choice unknowns with -нибудь as a reusable contrast in connected Russian.",
        exampleRu = "Open-choice unknowns with -нибудь",
        exampleEn = "Open-choice unknowns with -нибудь",
        hint = "Open-choice unknowns with -нибудь",
        order = 295,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf("INDEFINITE_TO"),
        interferesWith = listOf(),
        family = "INDEFINITES",
        stage = 2
    )

    val NEGATIVE_NI = GrammarConcept(
        id = "NEGATIVE_NI",
        title = "Negative pronouns with ни-",
        lesson = "This stage develops negative pronouns with ни- as a reusable contrast in connected Russian.",
        exampleRu = "Negative pronouns with ни-",
        exampleEn = "Negative pronouns with ни-",
        hint = "Negative pronouns with ни-",
        order = 315,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf("NEGATION_GENITIVE"),
        family = "NEGATION",
        stage = 1
    )

    val NEGATION_GENITIVE = GrammarConcept(
        id = "NEGATION_GENITIVE",
        title = "Genitive under negation",
        lesson = "This stage develops genitive under negation as a reusable contrast in connected Russian.",
        exampleRu = "Genitive under negation",
        exampleEn = "Genitive under negation",
        hint = "Genitive under negation",
        order = 335,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("NEGATIVE_NI"),
        interferesWith = listOf("NEGATIVE_NI"),
        family = "NEGATION",
        stage = 2
    )

    val THEME_RHEME = GrammarConcept(
        id = "THEME_RHEME",
        title = "Theme and new information",
        lesson = "This stage develops theme and new information as a reusable contrast in connected Russian.",
        exampleRu = "Theme and new information",
        exampleEn = "Theme and new information",
        hint = "Theme and new information",
        order = 315,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "INFORMATION_STRUCTURE",
        stage = 1
    )

    val FOCUS_ORDER = GrammarConcept(
        id = "FOCUS_ORDER",
        title = "Word order for contrastive focus",
        lesson = "This stage develops word order for contrastive focus as a reusable contrast in connected Russian.",
        exampleRu = "Word order for contrastive focus",
        exampleEn = "Word order for contrastive focus",
        hint = "Word order for contrastive focus",
        order = 345,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("THEME_RHEME"),
        interferesWith = listOf(),
        family = "INFORMATION_STRUCTURE",
        stage = 2
    )

    val PARTICIPLE_FORM = GrammarConcept(
        id = "PARTICIPLE_FORM",
        title = "Forming participles",
        lesson = "This stage develops forming participles as a reusable contrast in connected Russian.",
        exampleRu = "Forming participles",
        exampleEn = "Forming participles",
        hint = "Forming participles",
        order = 295,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PARTICIPLE",
        stage = 1
    )

    val PARTICIPLE_RECOGNIZE = GrammarConcept(
        id = "PARTICIPLE_RECOGNIZE",
        title = "Reading participial phrases",
        lesson = "This stage develops reading participial phrases as a reusable contrast in connected Russian.",
        exampleRu = "Reading participial phrases",
        exampleEn = "Reading participial phrases",
        hint = "Reading participial phrases",
        order = 325,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("PARTICIPLE_FORM"),
        interferesWith = listOf(),
        family = "PARTICIPLE",
        stage = 2
    )

    val PARTICIPLE_RELATIVE_TRANSFORM = GrammarConcept(
        id = "PARTICIPLE_RELATIVE_TRANSFORM",
        title = "Participle and который transformations",
        lesson = "This stage develops participle and который transformations as a reusable contrast in connected Russian.",
        exampleRu = "Participle and который transformations",
        exampleEn = "Participle and который transformations",
        hint = "Participle and который transformations",
        order = 355,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("PARTICIPLE_RECOGNIZE"),
        interferesWith = listOf(),
        family = "PARTICIPLE",
        stage = 3
    )

    val PARTICIPLE_PRODUCE = GrammarConcept(
        id = "PARTICIPLE_PRODUCE",
        title = "Producing formal participial clauses",
        lesson = "This stage develops producing formal participial clauses as a reusable contrast in connected Russian.",
        exampleRu = "Producing formal participial clauses",
        exampleEn = "Producing formal participial clauses",
        hint = "Producing formal participial clauses",
        order = 405,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf("PARTICIPLE_RELATIVE_TRANSFORM"),
        interferesWith = listOf(),
        family = "PARTICIPLE",
        stage = 4
    )

    val GERUND_SIMULTANEOUS = GrammarConcept(
        id = "GERUND_SIMULTANEOUS",
        title = "Simultaneous verbal adverbs",
        lesson = "This stage develops simultaneous verbal adverbs as a reusable contrast in connected Russian.",
        exampleRu = "Simultaneous verbal adverbs",
        exampleEn = "Simultaneous verbal adverbs",
        hint = "Simultaneous verbal adverbs",
        order = 325,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "GERUND",
        stage = 1
    )

    val GERUND_ANTERIOR = GrammarConcept(
        id = "GERUND_ANTERIOR",
        title = "Prior-action verbal adverbs",
        lesson = "This stage develops prior-action verbal adverbs as a reusable contrast in connected Russian.",
        exampleRu = "Prior-action verbal adverbs",
        exampleEn = "Prior-action verbal adverbs",
        hint = "Prior-action verbal adverbs",
        order = 365,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("GERUND_SIMULTANEOUS"),
        interferesWith = listOf(),
        family = "GERUND",
        stage = 2
    )

    val CONCESSIVE_HOTYA = GrammarConcept(
        id = "CONCESSIVE_HOTYA",
        title = "Concession with хотя",
        lesson = "This stage develops concession with хотя as a reusable contrast in connected Russian.",
        exampleRu = "Concession with хотя",
        exampleEn = "Concession with хотя",
        hint = "Concession with хотя",
        order = 305,
        spine = false,
        cefrLevel = "B2",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "CONCESSIVES",
        stage = 1
    )

    val CONCESSIVE_NESMOTRYA = GrammarConcept(
        id = "CONCESSIVE_NESMOTRYA",
        title = "Concession with несмотря на",
        lesson = "This stage develops concession with несмотря на as a reusable contrast in connected Russian.",
        exampleRu = "Concession with несмотря на",
        exampleEn = "Concession with несмотря на",
        hint = "Concession with несмотря на",
        order = 345,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("CONCESSIVE_HOTYA"),
        interferesWith = listOf(),
        family = "CONCESSIVES",
        stage = 2
    )

    val CONNECTIVES_FORMAL = GrammarConcept(
        id = "CONNECTIVES_FORMAL",
        title = "Formal connective contrasts",
        lesson = "This stage develops formal connective contrasts as a reusable contrast in connected Russian.",
        exampleRu = "Formal connective contrasts",
        exampleEn = "Formal connective contrasts",
        hint = "Formal connective contrasts",
        order = 385,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("CONCESSIVE_NESMOTRYA"),
        interferesWith = listOf(),
        family = "CONCESSIVES",
        stage = 3
    )

    val PARTICLE_ZHE = GrammarConcept(
        id = "PARTICLE_ZHE",
        title = "Discourse particle же",
        lesson = "This stage develops discourse particle же as a reusable contrast in connected Russian.",
        exampleRu = "Discourse particle же",
        exampleEn = "Discourse particle же",
        hint = "Discourse particle же",
        order = 335,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "PARTICLES",
        stage = 1
    )

    val PARTICLE_VED = GrammarConcept(
        id = "PARTICLE_VED",
        title = "Discourse particle ведь",
        lesson = "This stage develops discourse particle ведь as a reusable contrast in connected Russian.",
        exampleRu = "Discourse particle ведь",
        exampleEn = "Discourse particle ведь",
        hint = "Discourse particle ведь",
        order = 365,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf("PARTICLE_ZHE"),
        interferesWith = listOf(),
        family = "PARTICLES",
        stage = 2
    )

    val PARTICLE_TO = GrammarConcept(
        id = "PARTICLE_TO",
        title = "Contrastive particle -то",
        lesson = "This stage develops contrastive particle -то as a reusable contrast in connected Russian.",
        exampleRu = "Contrastive particle -то",
        exampleEn = "Contrastive particle -то",
        hint = "Contrastive particle -то",
        order = 395,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf("PARTICLE_VED"),
        interferesWith = listOf(),
        family = "PARTICLES",
        stage = 3
    )

    val PARTICLE_UZH = GrammarConcept(
        id = "PARTICLE_UZH",
        title = "Stance particle уж",
        lesson = "This stage develops stance particle уж as a reusable contrast in connected Russian.",
        exampleRu = "Stance particle уж",
        exampleEn = "Stance particle уж",
        hint = "Stance particle уж",
        order = 425,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf("PARTICLE_TO"),
        interferesWith = listOf(),
        family = "PARTICLES",
        stage = 4
    )

    val FORMAL_NEWS = GrammarConcept(
        id = "FORMAL_NEWS",
        title = "News-report register",
        lesson = "This stage develops news-report register as a reusable contrast in connected Russian.",
        exampleRu = "News-report register",
        exampleEn = "News-report register",
        hint = "News-report register",
        order = 355,
        spine = false,
        cefrLevel = "C1",
        prerequisites = listOf(),
        interferesWith = listOf(),
        family = "FORMAL_GENRES",
        stage = 1
    )

    val FORMAL_OFFICIAL = GrammarConcept(
        id = "FORMAL_OFFICIAL",
        title = "Official-statement register",
        lesson = "This stage develops official-statement register as a reusable contrast in connected Russian.",
        exampleRu = "Official-statement register",
        exampleEn = "Official-statement register",
        hint = "Official-statement register",
        order = 395,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf("FORMAL_NEWS"),
        interferesWith = listOf(),
        family = "FORMAL_GENRES",
        stage = 2
    )

    val FORMAL_ACADEMIC = GrammarConcept(
        id = "FORMAL_ACADEMIC",
        title = "Academic hedging and argumentation",
        lesson = "This stage develops academic hedging and argumentation as a reusable contrast in connected Russian.",
        exampleRu = "Academic hedging and argumentation",
        exampleEn = "Academic hedging and argumentation",
        hint = "Academic hedging and argumentation",
        order = 435,
        spine = false,
        cefrLevel = "C2",
        prerequisites = listOf("FORMAL_OFFICIAL"),
        interferesWith = listOf(),
        family = "FORMAL_GENRES",
        stage = 3
    )

    val ALL: List<GrammarConcept> = listOf(
        GEN_CHUNK_POSSESSION,
        GEN_CHUNK_ABSENCE,
        PREP_CHUNK_LOCATION,
        DAT_CHUNK_EXPERIENCER,
        INS_CHUNK_WITH,
        GENDER,
        NOM_PL,
        ACC,
        GEN,
        PREP,
        DAT,
        INS,
        PAST,
        ADJ_AGREE,
        PRESENT,
        ASPECT,
        FUTURE,
        IMPERATIVE,
        REFLEXIVE,
        COMPARATIVE,
        MODAL,
        MOTION,
        POSSESSIVE_SVOJ,
        MOTION_PREFIX,
        CONDITIONAL,
        RELATIVE,
        SUPERLATIVE,
        PURPOSE,
        NUMERAL_CASE,
        SHORT_FORM_ADJ,
        PARTICIPLE_ACTIVE,
        PARTICIPLE_PASSIVE,
        GERUND,
        PASSIVE,
        REPORTED,
        COMPLEX_SYNTAX,
        NOMINALIZATION,
        ASPECT_NUANCE,
        REGISTER,
        IDIOM,
        DISCOURSE_PARTICLES,
        EMPHATIC_PARTICLES,
        BOOKISH_SUBORDINATION,
        INVERSION_EMPHASIS,
        SUBJUNCTIVE_NUANCE,
        QUESTIONS,
        CONNECTORS_A_NO,
        CARDINALS,
        TIME_TELLING,
        ORDINALS_DATES,
        NUMERAL_GOV_234,
        NUMERAL_GOV_5,
        ASPECT_PAST,
        ASPECT_FUTURE,
        ASPECT_INFINITIVE,
        ASPECT_IMPERATIVE,
        ASPECT_NEGATION,
        MOTION_UNIDIRECTIONAL,
        MOTION_MULTIDIRECTIONAL,
        MOTION_CARRY,
        MOTION_TRANSPORT,
        MOTION_PREFIX_ARRIVE_LEAVE,
        MOTION_PREFIX_ENTER_EXIT,
        MOTION_PREFIX_APPROACH,
        MOTION_PREFIX_CROSS_PASS,
        GEN_PL,
        DAT_PL,
        INS_PL,
        PREP_PL,
        GOV_INTEREST_INS,
        GOV_FEAR_GEN,
        GOV_HELP_DAT,
        GOV_WAIT_GEN_ACC,
        GOV_DEPEND_ON,
        GOV_MANAGE_INS,
        GOV_USE_INS,
        GOV_CONGRAT_DAT,
        POSITION_STATE,
        POSITION_CAUSED,
        TIME_WEEK_ACC,
        TIME_MONTH_PREP,
        TIME_DURATION,
        TIME_DEADLINE,
        PREFIX_SEMANTICS,
        SUFFIX_OST,
        SUFFIX_ENIE,
        AGENT_SUFFIXES,
        DIMINUTIVES,
        ASPECT_PREFIXATION,
        INDEFINITE_TO,
        INDEFINITE_NIBUD,
        NEGATIVE_NI,
        NEGATION_GENITIVE,
        THEME_RHEME,
        FOCUS_ORDER,
        PARTICIPLE_FORM,
        PARTICIPLE_RECOGNIZE,
        PARTICIPLE_RELATIVE_TRANSFORM,
        PARTICIPLE_PRODUCE,
        GERUND_SIMULTANEOUS,
        GERUND_ANTERIOR,
        CONCESSIVE_HOTYA,
        CONCESSIVE_NESMOTRYA,
        CONNECTIVES_FORMAL,
        PARTICLE_ZHE,
        PARTICLE_VED,
        PARTICLE_TO,
        PARTICLE_UZH,
        FORMAL_NEWS,
        FORMAL_OFFICIAL,
        FORMAL_ACADEMIC,
    )

    private val byId: Map<String, GrammarConcept> = ALL.associateBy { it.id }

    fun byId(id: String?): GrammarConcept? = id?.let { byId[it] }

    val spineIds: Set<String> = ALL.filter { it.spine }.map { it.id }.toSet()

    fun forCard(card: Card): GrammarConcept? {
        card.gramConcept?.let { byId[it]?.let { c -> return c } }
        return when (card.cardType) {
            CardType.CASE_FILL -> byId(card.gramCase)
            CardType.GENDER_ID -> GENDER
            CardType.ADJ_AGREE -> ADJ_AGREE
            CardType.ASPECT_SELECT -> ASPECT
            CardType.CONCEPT_DRILL -> byId(card.gramConcept)
            CardType.VERB_FORM -> when {
                card.gramContextCue?.startsWith("PRES_") == true -> PRESENT
                else -> PAST
            }
            else -> null
        }
    }
}
