# Extended verb pairs for domain_wordlist.py
# 85 additional aspect pairs for formal/political/security register

EXTENDED_VERB_PAIRS = [
    # ── Diplomacy / Politics (15) ─────────────────────────────────────────
    ("запреща́ть", "запрети́ть", "to prohibit/ban", "accomplishment", "achievement"),
    ("ратифици́ровать", "", "to ratify", "accomplishment", "achievement", "bi"),
    ("аннекси́ровать", "", "to annex", "accomplishment", "achievement", "bi"),
    ("согласо́вывать", "согласова́ть", "to coordinate/agree upon", "accomplishment", "achievement"),
    ("координи́ровать", "скоордини́ровать", "to coordinate", "activity", "achievement"),
    ("отверга́ть", "отве́ргнуть", "to reject", "activity", "achievement"),
    ("одобря́ть", "одо́брить", "to approve", "accomplishment", "achievement"),
    ("голосова́ть", "проголосова́ть", "to vote", "activity", "achievement"),
    ("назнача́ть", "назна́чить", "to appoint", "accomplishment", "achievement"),
    ("утвержда́ть", "утверди́ть", "to approve/affirm", "accomplishment", "achievement"),
    ("избира́ть", "избра́ть", "to elect", "accomplishment", "achievement"),
    ("представля́ть", "предста́вить", "to present/represent", "accomplishment", "achievement"),
    ("выража́ть", "вы́разить", "to express", "activity", "achievement"),
    ("гаранти́ровать", "", "to guarantee", "accomplishment", "achievement", "bi"),
    ("реализо́вывать", "реализова́ть", "to implement", "accomplishment", "achievement"),

    # ── Military / Security (20) ──────────────────────────────────────────
    ("обстре́ливать", "обстреля́ть", "to shell/bombard", "activity", "achievement"),
    ("бомби́ть", "разбомби́ть", "to bomb", "activity", "achievement"),
    ("мобилизова́ть", "", "to mobilize", "accomplishment", "achievement", "bi"),
    ("демобилизова́ть", "", "to demobilize", "accomplishment", "achievement", "bi"),
    ("окружа́ть", "окружи́ть", "to encircle", "accomplishment", "achievement"),
    ("блоки́ровать", "заблоки́ровать", "to block/blockade", "activity", "achievement"),
    ("перехва́тывать", "перехвати́ть", "to intercept", "accomplishment", "achievement"),
    ("обнару́живать", "обнару́жить", "to detect/discover", "activity", "achievement"),
    ("размини́ровать", "", "to demine", "accomplishment", "achievement", "bi"),
    ("мини́ровать", "замини́ровать", "to mine (lay mines)", "accomplishment", "achievement"),
    ("эвакуи́ровать", "", "to evacuate", "accomplishment", "achievement", "bi"),
    ("патрули́ровать", "", "to patrol", "activity", "", "bi-skip"),
    ("вербова́ть", "завербова́ть", "to recruit", "accomplishment", "achievement"),
    ("дислоци́ровать", "", "to station/deploy", "accomplishment", "achievement", "bi"),
    ("капитули́ровать", "", "to capitulate", "activity", "achievement", "bi"),
    ("провоци́ровать", "спровоци́ровать", "to provoke", "activity", "achievement"),
    ("дестабилизи́ровать", "", "to destabilize", "accomplishment", "achievement", "bi"),
    ("конфискова́ть", "", "to confiscate", "accomplishment", "achievement", "bi"),
    ("ликвиди́ровать", "", "to liquidate/eliminate", "accomplishment", "achievement", "bi"),
    ("оккупи́ровать", "", "to occupy (territory)", "accomplishment", "achievement", "bi"),

    # ── Economy / Trade (15) ──────────────────────────────────────────────
    ("финанси́ровать", "профинанси́ровать", "to finance", "activity", "achievement"),
    ("субсиди́ровать", "", "to subsidize", "activity", "achievement", "bi"),
    ("инвести́ровать", "", "to invest", "activity", "achievement", "bi"),
    ("приватизи́ровать", "", "to privatize", "accomplishment", "achievement", "bi"),
    ("национализи́ровать", "", "to nationalize", "accomplishment", "achievement", "bi"),
    ("экспорти́ровать", "", "to export", "activity", "achievement", "bi"),
    ("импорти́ровать", "", "to import", "activity", "achievement", "bi"),
    ("девальви́ровать", "", "to devalue", "accomplishment", "achievement", "bi"),
    ("производи́ть", "произвести́", "to produce", "accomplishment", "achievement"),
    ("поставля́ть", "поста́вить", "to supply", "accomplishment", "achievement"),
    ("закупа́ть", "закупи́ть", "to purchase/procure", "accomplishment", "achievement"),
    ("выделя́ть", "вы́делить", "to allocate", "accomplishment", "achievement"),
    ("распределя́ть", "распредели́ть", "to distribute", "accomplishment", "achievement"),
    ("регули́ровать", "отрегули́ровать", "to regulate", "activity", "achievement"),
    ("модернизи́ровать", "", "to modernize", "accomplishment", "achievement", "bi"),

    # ── Legal / Investigative (10) ────────────────────────────────────────
    ("рассле́довать", "", "to investigate", "accomplishment", "achievement", "bi"),
    ("аресто́вывать", "арестова́ть", "to arrest", "accomplishment", "achievement"),
    ("заде́рживать", "задержа́ть", "to detain", "accomplishment", "achievement"),
    ("допра́шивать", "допроси́ть", "to interrogate", "activity", "achievement"),
    ("суди́ть", "", "to try/judge", "activity", "", "bi-skip"),
    ("пригова́ривать", "приговори́ть", "to sentence", "accomplishment", "achievement"),
    ("депорти́ровать", "", "to deport", "accomplishment", "achievement", "bi"),
    ("экстради́ровать", "", "to extradite", "accomplishment", "achievement", "bi"),
    ("амнисти́ровать", "", "to grant amnesty", "activity", "achievement", "bi"),
    ("обжа́ловать", "", "to appeal (a ruling)", "accomplishment", "achievement", "bi"),

    # ── Information / Communication (10) ──────────────────────────────────
    ("публикова́ть", "опубликова́ть", "to publish", "accomplishment", "achievement"),
    ("трансли́ровать", "", "to broadcast", "activity", "achievement", "bi"),
    ("информи́ровать", "проинформи́ровать", "to inform", "activity", "achievement"),
    ("комменти́ровать", "прокомменти́ровать", "to comment on", "activity", "achievement"),
    ("дезинформи́ровать", "", "to disinform", "activity", "", "bi-skip"),
    ("цензури́ровать", "", "to censor", "accomplishment", "achievement", "bi"),
    ("шифрова́ть", "зашифрова́ть", "to encrypt", "accomplishment", "achievement"),
    ("дешифрова́ть", "расшифрова́ть", "to decrypt/decipher", "accomplishment", "achievement"),
    ("пропаганди́ровать", "", "to propagandize", "activity", "", "bi-skip"),
    ("документи́ровать", "задокументи́ровать", "to document", "accomplishment", "achievement"),

    # ── General Formal (15) ──────────────────────────────────────────────
    ("формирова́ть", "сформирова́ть", "to form", "accomplishment", "achievement"),
    ("реформи́ровать", "", "to reform", "accomplishment", "achievement", "bi"),
    ("определя́ть", "определи́ть", "to determine/define", "accomplishment", "achievement"),
    ("устана́вливать", "установи́ть", "to establish/install", "accomplishment", "achievement"),
    ("разраба́тывать", "разрабо́тать", "to develop/elaborate", "accomplishment", "achievement"),
    ("осуществля́ть", "осуществи́ть", "to implement/carry out", "accomplishment", "achievement"),
    ("исключа́ть", "исключи́ть", "to exclude", "accomplishment", "achievement"),
    ("включа́ть", "включи́ть", "to include/switch on", "accomplishment", "achievement"),
    ("соде́йствовать", "посоде́йствовать", "to assist/facilitate", "activity", "achievement"),
    ("предотвраща́ть", "предотврати́ть", "to prevent", "accomplishment", "achievement"),
    ("восстана́вливать", "восстанови́ть", "to restore", "accomplishment", "achievement"),
    ("возобновля́ть", "возобнови́ть", "to resume", "accomplishment", "achievement"),
    ("приостана́вливать", "приостанови́ть", "to suspend", "accomplishment", "achievement"),
    ("прекраща́ть", "прекрати́ть", "to cease/terminate", "accomplishment", "achievement"),
    ("продолжа́ть", "продо́лжить", "to continue", "activity", "achievement"),
]

# Additional motion verbs
EXTENDED_MOTION_VERBS = [
    ("перемеща́ться", "перемести́ться", "to move/relocate", "activity", "achievement", "motion"),
    ("переправля́ться", "перепра́виться", "to cross (a body of water)", "activity", "achievement", "motion"),
    ("доставля́ть", "доста́вить", "to deliver/transport", "accomplishment", "achievement", "motion"),
    ("перебра́сывать", "перебро́сить", "to redeploy/transfer", "accomplishment", "achievement", "motion"),
    ("вылета́ть", "вы́лететь", "to fly out/depart (by air)", "activity", "achievement", "motion"),
]
