# Extended nouns and adjectives for domain_wordlist.py
# Exactly 250 nouns and exactly 50 adjectives for formal/political/security register

EXTENDED_NOUNS = [
    ('ОО́Н', 'indecl', 'UN', False, 'SG'),
    ('НА́ТО', 'indecl', 'NATO', False, 'SG'),
    ('ОБСЕ́', 'indecl', 'OSCE', False, 'SG'),
    ('Евросою́з', 'm_hard', 'European Union', False, 'SG'),
    ('ЮНЕ́СКО', 'indecl', 'UNESCO', False, 'SG'),
    ('ВОЗ', 'indecl', 'WHO', False, 'SG'),
    ('МВФ', 'indecl', 'IMF', False, 'SG'),
    ('БРИКС', 'm_hard', 'BRICS', False, 'SG'),
    ('коали́ция', 'f_iya', 'coalition', False, 'SG+PL'),
    ('алья́нс', 'm_hard', 'alliance', False, 'SG+PL'),
    ('диплома́т', 'm_hard', 'diplomat', True, 'SG+PL'),
    ('консу́льство', 'n_o', 'consulate', False, 'SG+PL'),
    ('ко́нсул', 'm_hard', 'consul', True, 'SG+PL'),
    ('атташе́', 'indecl', 'attaché', True, 'SG+PL'),
    ('мемора́ндум', 'm_hard', 'memorandum', False, 'SG+PL'),
    ('пакт', 'm_hard', 'pact', False, 'SG+PL'),
    ('конве́нция', 'f_iya', 'convention', False, 'SG+PL'),
    ('консе́нсус', 'm_hard', 'consensus', False, 'SG'),
    ('ратифика́ция', 'f_iya', 'ratification', False, 'SG'),
    ('посре́дничество', 'n_o', 'mediation', False, 'SG'),
    ('посре́дник', 'm_hard', 'mediator', True, 'SG+PL'),
    ('посла́нник', 'm_hard', 'envoy', True, 'SG+PL'),
    ('эмисса́р', 'm_hard', 'emissary', True, 'SG+PL'),
    ('переговори́щик', 'm_hard', 'negotiator', True, 'SG+PL'),
    ('дипко́рпус', 'm_hard', 'diplomatic corps', False, 'SG'),
    ('но́та', 'f_a', 'note', False, 'SG+PL'),
    ('ультима́тум', 'm_hard', 'ultimatum', False, 'SG+PL'),
    ('суверените́т', 'm_hard', 'sovereignty', False, 'SG'),
    ('призна́ние', 'n_ie', 'recognition', False, 'SG'),
    ('интегра́ция', 'f_iya', 'integration', False, 'SG'),
    ('глобализа́ция', 'f_iya', 'globalization', False, 'SG'),
    ('изоля́ция', 'f_iya', 'isolation', False, 'SG'),
    ('конфронта́ция', 'f_iya', 'confrontation', False, 'SG+PL'),
    ('партнёрство', 'n_o', 'partnership', False, 'SG'),
    ('содру́жество', 'n_o', 'commonwealth', False, 'SG'),
    ('председа́тельство', 'n_o', 'presidency/chairmanship', False, 'SG'),
    ('дема́рш', 'm_hard', 'demarche', False, 'SG+PL'),
    ('регла́мент', 'm_hard', 'regulations', False, 'SG+PL'),
    ('парите́т', 'm_hard', 'parity', False, 'SG'),
    ('ста́тус-кво', 'indecl', 'status quo', False, 'SG'),
    ('репатриа́ция', 'f_iya', 'repatriation', False, 'SG'),
    ('депорта́ция', 'f_iya', 'deportation', False, 'SG+PL'),
    ('экспатриа́ция', 'f_iya', 'expatriation', False, 'SG'),
    ('ви́за', 'f_a', 'visa', False, 'SG+PL'),
    ('аккредита́ция', 'f_iya', 'accreditation', False, 'SG'),
    ('премье́р-мини́стр', 'm_hard', 'prime minister', True, 'SG+PL'),
    ('ви́це-президе́нт', 'm_hard', 'vice president', True, 'SG+PL'),
    ('губерна́тор', 'm_hard', 'governor', True, 'SG+PL'),
    ('мэр', 'm_hard', 'mayor', True, 'SG+PL'),
    ('админи́страция', 'f_iya', 'administration', False, 'SG+PL'),
    ('госаппара́т', 'm_hard', 'state apparatus', False, 'SG'),
    ('чино́вник', 'm_hard', 'official', True, 'SG+PL'),
    ('представи́тель', 'm_soft', 'representative', True, 'SG+PL'),
    ('руково́дство', 'n_o', 'leadership', False, 'SG'),
    ('глава́', 'f_a', 'head/chief', True, 'SG+PL'),
    ('предводи́тель', 'm_soft', 'leader', True, 'SG+PL'),
    ('председа́тель', 'm_soft', 'chairman', True, 'SG+PL'),
    ('сена́тор', 'm_hard', 'senator', True, 'SG+PL'),
    ('спи́кер', 'm_hard', 'speaker', True, 'SG+PL'),
    ('ка́бинет', 'm_hard', 'cabinet', False, 'SG+PL'),
    ('департа́мент', 'm_hard', 'department', False, 'SG+PL'),
    ('федера́ция', 'f_iya', 'federation', False, 'SG+PL'),
    ('респу́блика', 'f_a', 'republic', False, 'SG+PL'),
    ('мона́рхия', 'f_iya', 'monarchy', False, 'SG+PL'),
    ('диктату́ра', 'f_a', 'dictatorship', False, 'SG+PL'),
    ('режи́м', 'm_hard', 'regime', False, 'SG+PL'),
    ('ве́то', 'indecl', 'veto', False, 'SG'),
    ('се́ссия', 'f_iya', 'session', False, 'SG+PL'),
    ('пле́нум', 'm_hard', 'plenum', False, 'SG+PL'),
    ('бюллете́нь', 'm_soft', 'ballot', False, 'SG+PL'),
    ('избира́тель', 'm_soft', 'voter', True, 'SG+PL'),
    ('электора́т', 'm_hard', 'electorate', False, 'SG'),
    ('кампа́ния', 'f_iya', 'campaign', False, 'SG+PL'),
    ('инаугура́ция', 'f_iya', 'inauguration', False, 'SG'),
    ('прися́га', 'f_a', 'oath', False, 'SG'),
    ('штаб', 'm_hard', 'headquarters/staff', False, 'SG+PL'),
    ('флот', 'm_hard', 'fleet', False, 'SG+PL'),
    ('полк', 'm_hard', 'regiment', False, 'SG+PL'),
    ('батальо́н', 'm_hard', 'battalion', False, 'SG+PL'),
    ('брига́да', 'f_a', 'brigade', False, 'SG+PL'),
    ('диви́зия', 'f_iya', 'division', False, 'SG+PL'),
    ('ко́рпус', 'm_hard', 'corps', False, 'SG+PL'),
    ('взвод', 'm_hard', 'platoon', False, 'SG+PL'),
    ('ро́та', 'f_a', 'company', False, 'SG+PL'),
    ('гарнизо́н', 'm_hard', 'garrison', False, 'SG+PL'),
    ('фронт', 'm_hard', 'front', False, 'SG+PL'),
    ('тыл', 'm_hard', 'rear/home front', False, 'SG'),
    ('фланг', 'm_hard', 'flank', False, 'SG+PL'),
    ('плацда́рм', 'm_hard', 'bridgehead', False, 'SG+PL'),
    ('око́п', 'm_hard', 'trench', False, 'SG+PL'),
    ('блинда́ж', 'm_hard', 'bunker', False, 'SG+PL'),
    ('блокпо́ст', 'm_hard', 'checkpoint', False, 'SG+PL'),
    ('укрепле́ние', 'n_ie', 'fortification', False, 'SG+PL'),
    ('рубе́ж', 'm_hard', 'line/border', False, 'SG+PL'),
    ('боеприпа́с', 'm_hard', 'ammunition', False, 'SG+PL'),
    ('снаря́д', 'm_hard', 'shell/projectile', False, 'SG+PL'),
    ('патро́н', 'm_hard', 'cartridge/round', False, 'SG+PL'),
    ('ми́на', 'f_a', 'mine (explosive)', False, 'SG+PL'),
    ('грана́та', 'f_a', 'grenade', False, 'SG+PL'),
    ('бо́мба', 'f_a', 'bomb', False, 'SG+PL'),
    ('беспило́тник', 'm_hard', 'drone/UAV', False, 'SG+PL'),
    ('авиано́сец', 'm_hard', 'aircraft carrier', False, 'SG+PL'),
    ('кре́йсер', 'm_hard', 'cruiser', False, 'SG+PL'),
    ('эсми́нец', 'm_hard', 'destroyer', False, 'SG+PL'),
    ('субмари́на', 'f_a', 'submarine', False, 'SG+PL'),
    ('истреби́тель', 'm_soft', 'fighter jet', False, 'SG+PL'),
    ('бомбардиро́вщик', 'm_hard', 'bomber', False, 'SG+PL'),
    ('вертолёт', 'm_hard', 'helicopter', False, 'SG+PL'),
    ('бронетехника', 'f_a', 'armored vehicles', False, 'SG'),
    ('танк', 'm_hard', 'tank', False, 'SG+PL'),
    ('бронетранспортёр', 'm_hard', 'armored personnel carrier', False, 'SG+PL'),
    ('га́убица', 'f_a', 'howitzer', False, 'SG+PL'),
    ('артилле́рия', 'f_iya', 'artillery', False, 'SG'),
    ('пехо́та', 'f_a', 'infantry', False, 'SG'),
    ('кавале́рия', 'f_iya', 'cavalry', False, 'SG'),
    ('деса́нт', 'm_hard', 'landing force', False, 'SG+PL'),
    ('миротво́рец', 'm_hard', 'peacekeeper', True, 'SG+PL'),
    ('наёмник', 'm_hard', 'mercenary', True, 'SG+PL'),
    ('ополче́нец', 'm_hard', 'militiaman', True, 'SG+PL'),
    ('партиза́н', 'm_hard', 'partisan/guerrilla', True, 'SG+PL'),
    ('диверса́нт', 'm_hard', 'saboteur', True, 'SG+PL'),
    ('шпио́н', 'm_hard', 'spy', True, 'SG+PL'),
    ('шпиона́ж', 'm_hard', 'espionage', False, 'SG'),
    ('сабота́ж', 'm_hard', 'sabotage', False, 'SG'),
    ('диве́рсия', 'f_iya', 'diversion/sabotage', False, 'SG+PL'),
    ('провока́ция', 'f_iya', 'provocation', False, 'SG+PL'),
    ('вербо́вка', 'f_a', 'recruitment', False, 'SG'),
    ('сле́жка', 'f_a', 'surveillance/tracking', False, 'SG'),
    ('прослу́шка', 'f_a', 'wiretapping', False, 'SG'),
    ('кибербезопа́сность', 'f_soft', 'cybersecurity', False, 'SG'),
    ('киберата́ка', 'f_a', 'cyberattack', False, 'SG+PL'),
    ('экстреми́зм', 'm_hard', 'extremism', False, 'SG'),
    ('радикализа́ция', 'f_iya', 'radicalization', False, 'SG'),
    ('ВВП', 'indecl', 'GDP', False, 'SG'),
    ('акцио́нер', 'm_hard', 'shareholder', True, 'SG+PL'),
    ('а́кция', 'f_iya', 'share/stock', False, 'SG+PL'),
    ('би́ржа', 'f_a', 'stock exchange', False, 'SG+PL'),
    ('дивиде́нд', 'm_hard', 'dividend', False, 'SG+PL'),
    ('субси́дия', 'f_iya', 'subsidy', False, 'SG+PL'),
    ('тари́ф', 'm_hard', 'tariff', False, 'SG+PL'),
    ('кво́та', 'f_a', 'quota', False, 'SG+PL'),
    ('дефици́т', 'm_hard', 'deficit', False, 'SG+PL'),
    ('профици́т', 'm_hard', 'surplus', False, 'SG+PL'),
    ('дохо́д', 'm_hard', 'income/revenue', False, 'SG+PL'),
    ('расхо́д', 'm_hard', 'expense/expenditure', False, 'SG+PL'),
    ('прибы́ль', 'f_soft', 'profit', False, 'SG+PL'),
    ('убы́ток', 'm_hard', 'loss/damage', False, 'SG+PL'),
    ('нало́г', 'm_hard', 'tax', False, 'SG+PL'),
    ('сбо́р', 'm_hard', 'fee/levy/collection', False, 'SG+PL'),
    ('акти́в', 'm_hard', 'asset', False, 'SG+PL'),
    ('обяза́тельство', 'n_o', 'obligation/liability', False, 'SG+PL'),
    ('креди́т', 'm_hard', 'credit/loan', False, 'SG+PL'),
    ('заём', 'm_hard', 'loan', False, 'SG+PL'),
    ('инве́стор', 'm_hard', 'investor', True, 'SG+PL'),
    ('кредито́р', 'm_hard', 'creditor', True, 'SG+PL'),
    ('заёмщик', 'm_hard', 'borrower', True, 'SG+PL'),
    ('транш', 'm_hard', 'tranche', False, 'SG+PL'),
    ('капита́л', 'm_hard', 'capital', False, 'SG+PL'),
    ('инвести́рование', 'n_ie', 'investing', False, 'SG'),
    ('приватиза́ция', 'f_iya', 'privatization', False, 'SG'),
    ('национализа́ция', 'f_iya', 'nationalization', False, 'SG'),
    ('девальва́ция', 'f_iya', 'devaluation', False, 'SG'),
    ('дефо́лт', 'm_hard', 'default', False, 'SG+PL'),
    ('банкро́тство', 'n_o', 'bankruptcy', False, 'SG'),
    ('реце́ссия', 'f_iya', 'recession', False, 'SG'),
    ('стагна́ция', 'f_iya', 'stagnation', False, 'SG'),
    ('ВТО', 'indecl', 'WTO', False, 'SG'),
    ('протекциони́зм', 'm_hard', 'protectionism', False, 'SG'),
    ('электроста́нция', 'f_iya', 'power plant', False, 'SG+PL'),
    ('мо́щность', 'f_soft', 'power/capacity', False, 'SG+PL'),
    ('генера́ция', 'f_iya', 'generation', False, 'SG'),
    ('сеть', 'f_soft', 'grid/network', False, 'SG+PL'),
    ('энергобло́к', 'm_hard', 'power unit', False, 'SG+PL'),
    ('реакто́р', 'm_hard', 'reactor', False, 'SG+PL'),
    ('АЭС', 'indecl', 'nuclear power plant', False, 'SG'),
    ('ГЭС', 'indecl', 'hydroelectric power plant', False, 'SG'),
    ('ТЭЦ', 'indecl', 'combined heat and power plant', False, 'SG'),
    ('ЛЭП', 'indecl', 'power transmission line', False, 'SG'),
    ('нефтепрово́д', 'm_hard', 'oil pipeline', False, 'SG+PL'),
    ('газопрово́д', 'm_hard', 'gas pipeline', False, 'SG+PL'),
    ('транзи́т', 'm_hard', 'transit', False, 'SG'),
    ('инфраструкту́ра', 'f_a', 'infrastructure', False, 'SG'),
    ('то́пливо', 'n_o', 'fuel', False, 'SG'),
    ('прокуро́р', 'm_hard', 'prosecutor', True, 'SG+PL'),
    ('адвока́т', 'm_hard', 'advocate/lawyer', True, 'SG+PL'),
    ('арбитра́ж', 'm_hard', 'arbitration', False, 'SG+PL'),
    ('иск', 'm_hard', 'lawsuit/claim', False, 'SG+PL'),
    ('пригово́р', 'm_hard', 'sentence/verdict', False, 'SG+PL'),
    ('задержа́ние', 'n_ie', 'detention/arrest', False, 'SG+PL'),
    ('экстради́ция', 'f_iya', 'extradition', False, 'SG'),
    ('юри́ст', 'm_hard', 'jurist/lawyer', True, 'SG+PL'),
    ('обвини́тель', 'm_soft', 'prosecutor/accuser', True, 'SG+PL'),
    ('правонаруши́тель', 'm_soft', 'offender/lawbreaker', True, 'SG+PL'),
    ('апелля́ция', 'f_iya', 'appeal', False, 'SG+PL'),
    ('амни́стия', 'f_iya', 'amnesty', False, 'SG+PL'),
    ('верди́кт', 'm_hard', 'verdict', False, 'SG+PL'),
    ('ко́декс', 'm_hard', 'code', False, 'SG+PL'),
    ('законопрое́кт', 'm_hard', 'bill/draft law', False, 'SG+PL'),
    ('попра́вка', 'f_a', 'amendment', False, 'SG+PL'),
    ('прецеде́нт', 'm_hard', 'precedent', False, 'SG+PL'),
    ('ре́плика', 'f_a', 'remark/replica', False, 'SG+PL'),
    ('сле́дствие', 'n_ie', 'investigation/inquiry', False, 'SG+PL'),
    ('допро́с', 'm_hard', 'interrogation', False, 'SG+PL'),
    ('обы́ск', 'm_hard', 'search (by police)', False, 'SG+PL'),
    ('ули́ка', 'f_a', 'piece of evidence', False, 'SG+PL'),
    ('подозре́ние', 'n_ie', 'suspicion', False, 'SG+PL'),
    ('правосу́дие', 'n_ie', 'justice', False, 'SG'),
    ('зако́нность', 'f_soft', 'legality/lawfulness', False, 'SG'),
    ('жа́лоба', 'f_a', 'complaint/appeal', False, 'SG+PL'),
    ('претензи́я', 'f_iya', 'claim/grievance', False, 'SG+PL'),
    ('санкциони́рование', 'n_ie', 'authorization', False, 'SG'),
    ('юрисди́кция', 'f_iya', 'jurisdiction', False, 'SG+PL'),
    ('конфиска́ция', 'f_iya', 'confiscation', False, 'SG'),
    ('журнали́ст', 'm_hard', 'journalist', True, 'SG+PL'),
    ('корреспонде́нт', 'm_hard', 'correspondent', True, 'SG+PL'),
    ('реда́кция', 'f_iya', 'editorial office', False, 'SG+PL'),
    ('публика́ция', 'f_iya', 'publication', False, 'SG+PL'),
    ('анали́тика', 'f_a', 'analytics', False, 'SG'),
    ('репорта́ж', 'm_hard', 'reportage/report', False, 'SG+PL'),
    ('цензу́ра', 'f_a', 'censorship', False, 'SG'),
    ('бри́финг', 'm_hard', 'briefing', False, 'SG+PL'),
    ('комменти́рование', 'n_ie', 'commenting', False, 'SG'),
    ('трансля́ция', 'f_iya', 'broadcast', False, 'SG+PL'),
    ('пропага́нда', 'f_a', 'propaganda', False, 'SG'),
    ('пресс-рели́з', 'm_hard', 'press release', False, 'SG+PL'),
    ('веща́ние', 'n_ie', 'broadcasting', False, 'SG'),
    ('фейк', 'm_hard', 'fake/hoax', False, 'SG+PL'),
    ('огла́ска', 'f_a', 'publicity/disclosure', False, 'SG'),
    ('террито́рия', 'f_iya', 'territory', False, 'SG+PL'),
    ('регио́н', 'm_hard', 'region', False, 'SG+PL'),
    ('райо́н', 'm_hard', 'district/area', False, 'SG+PL'),
    ('о́бласть', 'f_soft', 'oblast/province', False, 'SG+PL'),
    ('зо́на', 'f_a', 'zone', False, 'SG+PL'),
    ('аквато́рия', 'f_iya', 'water area', False, 'SG+PL'),
    ('пери́метр', 'm_hard', 'perimeter', False, 'SG+PL'),
    ('контине́нт', 'm_hard', 'continent', False, 'SG+PL'),
    ('се́ктор', 'm_hard', 'sector', False, 'SG+PL'),
    ('анкла́в', 'm_hard', 'enclave', False, 'SG+PL'),
    ('экскла́в', 'm_hard', 'exclave', False, 'SG+PL'),
    ('прови́нция', 'f_iya', 'province', False, 'SG+PL'),
    ('о́круг', 'm_hard', 'district/okrug', False, 'SG+PL'),
    ('плато́', 'indecl', 'plateau', False, 'SG'),
    ('шельф', 'm_hard', 'continental shelf', False, 'SG+PL'),
    ('населе́ние', 'n_ie', 'population', False, 'SG'),
    ('гражда́нство', 'n_o', 'citizenship', False, 'SG'),
    ('мигра́нт', 'm_hard', 'migrant', True, 'SG+PL'),
    ('демогра́фия', 'f_iya', 'demography', False, 'SG'),
    ('диа́спора', 'f_a', 'diaspora', False, 'SG+PL'),
    ('гумани́зм', 'm_hard', 'humanism', False, 'SG'),
    ('катастро́фа', 'f_a', 'catastrophe/disaster', False, 'SG+PL'),
]

EXTENDED_ADJECTIVES = [
    ('террористи́ческий', 'terrorist'),
    ('гуманита́рный', 'humanitarian'),
    ('территориа́льный', 'territorial'),
    ('внешнеполити́ческий', 'foreign-policy'),
    ('вну́тренний', 'internal/domestic'),
    ('вне́шний', 'external/foreign'),
    ('пограни́чный', 'border/frontier'),
    ('противовозду́шный', 'anti-aircraft/air-defense'),
    ('баллисти́ческий', 'ballistic'),
    ('гиперзвуково́й', 'hypersonic'),
    ('межконтинента́льный', 'intercontinental'),
    ('косми́ческий', 'space/cosmic'),
    ('морско́й', 'sea/marine'),
    ('сухопу́тный', 'land/overland'),
    ('возду́шный', 'air/aerial'),
    ('подво́дный', 'underwater/submarine'),
    ('разве́дывательный', 'reconnaissance/intelligence'),
    ('операти́вный', 'operational'),
    ('миротво́рческий', 'peacekeeping'),
    ('консу́льский', 'consular'),
    ('посо́льский', 'embassy (adj.)'),
    ('прави́тельственный', 'governmental'),
    ('президе́нтский', 'presidential'),
    ('министе́рский', 'ministerial'),
    ('парла́ментский', 'parliamentary'),
    ('законода́тельный', 'legislative'),
    ('исполни́тельный', 'executive'),
    ('суде́бный', 'judicial/court (adj.)'),
    ('прокуро́рский', 'prosecutorial'),
    ('адвока́тский', 'advocacy/lawyer (adj.)'),
    ('юриди́ческий', 'legal/juridical'),
    ('уголо́вный', 'criminal'),
    ('администрати́вный', 'administrative'),
    ('конституцио́нный', 'constitutional'),
    ('муниципа́льный', 'municipal'),
    ('коалицио́нный', 'coalition (adj.)'),
    ('сою́зный', 'union/allied'),
    ('партнёрский', 'partner (adj.)'),
    ('экстреми́стский', 'extremist'),
    ('сепарати́стский', 'separatist'),
    ('радика́льный', 'radical'),
    ('идеологи́ческий', 'ideological'),
    ('пропаганди́стский', 'propaganda (adj.)'),
    ('автоно́мный', 'autonomous'),
    ('провокацио́нный', 'provocative'),
    ('легити́мный', 'legitimate'),
    ('геополити́ческий', 'geopolitical'),
    ('многонациона́льный', 'multinational'),
    ('информацио́нный', 'information/informational'),
    ('зако́нный', 'legal/lawful'),
]
