# -*- coding: utf-8 -*-
"""Generate app/src/main/java/com/sibirskyspeak/data/GrammarConcepts.kt from concepts.json

Usage:
    python tools/preprocess/generate_concepts.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
JSON_FILE = REPO_ROOT / "tools/preprocess/concepts.json"
KT_FILE = REPO_ROOT / "app/src/main/java/com/sibirskyspeak/data/GrammarConcepts.kt"

def validate_and_expand():
    if not JSON_FILE.exists():
        print(f"Error: {JSON_FILE} not found.", file=sys.stderr)
        sys.exit(1)
        
    data = json.loads(JSON_FILE.read_text(encoding="utf-8"))
    core_concepts = data["core_concepts"]
    staged_specs = data["staged_specs"]
    
    # 1. Expand staged specs
    spine_2 = []
    family_roots = {
        "ASPECT": "ASPECT", "MOTION": "MOTION", "MOTION_PREFIX": "MOTION_PREFIX",
        "TIME": "TIME_TELLING", "PARTICIPLE": "PARTICIPLE_ACTIVE", "GERUND": "GERUND"
    }
    for spec in staged_specs:
        spec_id = spec["id"]
        family = spec["family"]
        stage = spec["stage"]
        title = spec["title"]
        order = spec["order"]
        band = spec["band"]
        
        # Previous stage in same family
        prev_spec = next((s["id"] for s in staged_specs if s["family"] == family and s["stage"] == stage - 1), None)
        previous = prev_spec if prev_spec else (family_roots.get(family) if stage > 1 else None)
        
        # Interference
        interference_families = {"ASPECT", "MOTION", "MOTION_PREFIX", "CASE_PLURAL", "GOVERNMENT", "NEGATION"}
        if family in interference_families:
            interference = [s["id"] for s in staged_specs if s["family"] == family and s["id"] != spec_id][:4]
        else:
            interference = []
            
        spine_2.append({
            "id": spec_id,
            "title": title,
            "lesson": f"This stage develops {title.lower()} as a reusable contrast in connected Russian.",
            "exampleRu": title,
            "exampleEn": title,
            "hint": title,
            "order": order,
            "spine": False,
            "cefrLevel": band,
            "prerequisites": [previous] if previous else [],
            "interferesWith": interference,
            "family": family,
            "stage": stage
        })
        
    all_concepts = core_concepts + spine_2
    
    # 2. Validations
    # Check duplicate IDs
    ids = [c["id"] for c in all_concepts]
    duplicates = set(x for x in ids if ids.count(x) > 1)
    if duplicates:
        print(f"Error: Duplicate concept IDs found: {duplicates}", file=sys.stderr)
        sys.exit(1)
        
    concept_map = {c["id"]: c for c in all_concepts}
    
    # Check invalid prerequisites or interference targets
    for c in all_concepts:
        for p in c["prerequisites"]:
            if p not in concept_map:
                print(f"Error: Concept '{c['id']}' has unknown prerequisite '{p}'", file=sys.stderr)
                sys.exit(1)
        for i in c["interferesWith"]:
            if i not in concept_map:
                print(f"Error: Concept '{c['id']}' has unknown interference target '{i}'", file=sys.stderr)
                sys.exit(1)
                
    # Detect cycles in prerequisites
    visited = {}
    def visit(node_id, visiting):
        if node_id in visiting:
            print(f"Error: Grammar prerequisite cycle detected at '{node_id}'", file=sys.stderr)
            sys.exit(1)
        if node_id in visited:
            return
        visiting.add(node_id)
        for prereq in concept_map[node_id]["prerequisites"]:
            visit(prereq, visiting)
        visiting.remove(node_id)
        visited[node_id] = True
        
    for c in all_concepts:
        visit(c["id"], set())
        
    # Generate GrammarConcepts.kt content
    lines = [
        "package com.sibirskyspeak.data",
        "",
        "import com.sibirskyspeak.data.Card",
        "import com.sibirskyspeak.data.CardType",
        "",
        "// Generated by generate_concepts.py. Do not edit manually.",
        "",
        "data class GrammarConcept(",
        "    val id: String,",
        "    val title: String,",
        "    val lesson: String,",
        "    val exampleRu: String,",
        "    val exampleEn: String,",
        "    val hint: String,",
        "    val order: Int,",
        "    val spine: Boolean = true,",
        "    val cefrLevel: String,",
        "    val prerequisites: List<String> = emptyList(),",
        "    val interferesWith: List<String> = emptyList(),",
        "    val family: String = id.substringBefore('_'),",
        "    val stage: Int = 1",
        ")",
        "",
        "object GrammarConcepts {"
    ]
    
    # Write each concept variable
    for c in all_concepts:
        lines.append(f"    val {c['id']} = GrammarConcept(")
        lines.append(f"        id = \"{c['id']}\",")
        def escape_kt(s: str) -> str:
            return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')
        lines.append(f"        title = \"{escape_kt(c['title']).replace('&', '&amp;')}\",")
        lines.append(f"        lesson = \"{escape_kt(c['lesson'])}\",")
        lines.append(f"        exampleRu = \"{escape_kt(c['exampleRu'])}\",")
        lines.append(f"        exampleEn = \"{escape_kt(c['exampleEn'])}\",")
        lines.append(f"        hint = \"{escape_kt(c['hint'])}\",")
        lines.append(f"        order = {c['order']},")
        lines.append(f"        spine = {str(c['spine']).lower()},")
        lines.append(f"        cefrLevel = \"{c['cefrLevel']}\",")
        
        prereqs_str = ", ".join(f'"{p}"' for p in c['prerequisites'])
        lines.append(f"        prerequisites = listOf({prereqs_str}),")
        
        interfere_str = ", ".join(f'"{i}"' for i in c['interferesWith'])
        lines.append(f"        interferesWith = listOf({interfere_str}),")
        
        lines.append(f"        family = \"{c['family']}\",")
        lines.append(f"        stage = {c['stage']}")
        lines.append("    )")
        lines.append("")
        
    # Write ALL collection
    lines.append("    val ALL: List<GrammarConcept> = listOf(")
    # List them all
    for c in all_concepts:
        lines.append(f"        {c['id']},")
    lines.append("    )")
    lines.append("")
    
    lines.append("    private val byId: Map<String, GrammarConcept> = ALL.associateBy { it.id }")
    lines.append("")
    lines.append("    fun byId(id: String?): GrammarConcept? = id?.let { byId[it] }")
    lines.append("")
    lines.append("    val spineIds: Set<String> = ALL.filter { it.spine }.map { it.id }.toSet()")
    lines.append("")
    lines.append("    fun forCard(card: Card): GrammarConcept? {")
    lines.append("        card.gramConcept?.let { byId[it]?.let { c -> return c } }")
    lines.append("        return when (card.cardType) {")
    lines.append("            CardType.CASE_FILL -> byId(card.gramCase)")
    lines.append("            CardType.GENDER_ID -> GENDER")
    lines.append("            CardType.ADJ_AGREE -> ADJ_AGREE")
    lines.append("            CardType.ASPECT_SELECT -> ASPECT")
    lines.append("            CardType.CONCEPT_DRILL -> byId(card.gramConcept)")
    lines.append("            CardType.VERB_FORM -> when {")
    lines.append("                card.gramContextCue?.startsWith(\"PRES_\") == true -> PRESENT")
    lines.append("                else -> PAST")
    lines.append("            }")
    lines.append("            else -> null")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    
    # Write file
    KT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {KT_FILE.name} with {len(all_concepts)} concepts successfully.")

if __name__ == "__main__":
    validate_and_expand()
