"""Curated vocabulary supplement to give the bundled reader texts full offline
coverage. These are the content lemmas that appear in the (advanced/authentic)
reader texts but weren't in the deck. Adding the LEMMA is enough: the app's
morphology (RussianForms) generates the inflected forms (past/present, full noun
and adjective declension), so e.g. adding "поставка" resolves "поставок".

Each entry is (lemma, pos, english_gloss). russian headword == lemma.
Glosses are concise dictionary definitions. pos drives form generation:
  verb -> past + present forms; noun -> declension; adj -> declension + comparative.
Participles are tagged pos="adj" so their adjectival forms decline.
"""

# (lemma, pos, gloss)
ENTRIES = [
    # --- verbs (infinitive; past/present generated) ---
    ("отметить", "verb", "to note, to mention"),
    ("подчёркивать", "verb", "to emphasize"),
    ("подчеркнуть", "verb", "to emphasize, to stress"),
    ("подрывать", "verb", "to undermine"),
    ("предупредить", "verb", "to warn"),
    ("договориться", "verb", "to agree, to come to terms"),
    ("провести", "verb", "to conduct, to hold, to spend (time)"),
    ("открыть", "verb", "to open"),
    ("оставаться", "verb", "to remain, to stay"),
    ("планировать", "verb", "to plan"),
    ("снизить", "verb", "to lower, to reduce"),
    ("снизиться", "verb", "to decrease, to drop"),
    ("получить", "verb", "to receive, to get"),
    ("смочь", "verb", "to be able to"),
    ("сказать", "verb", "to say, to tell"),
    ("помочь", "verb", "to help"),
    ("согласиться", "verb", "to agree"),
    ("стоять", "verb", "to stand; to cost"),
    ("достичь", "verb", "to achieve, to reach"),
    ("потерять", "verb", "to lose"),
    ("подвести", "verb", "to let down; to sum up"),
    ("привлекать", "verb", "to attract; to involve"),
    ("составить", "verb", "to compose; to amount to"),
    ("привести", "verb", "to bring; to lead to"),
    ("повысить", "verb", "to raise, to increase"),
    ("прогнозировать", "verb", "to forecast"),
    ("ускорить", "verb", "to speed up, to accelerate"),
    ("обратить", "verb", "to turn, to draw (attention)"),
    ("опровергнуть", "verb", "to refute, to deny"),
    ("встретить", "verb", "to meet"),
    ("встретиться", "verb", "to meet (with someone)"),
    ("уехать", "verb", "to leave, to depart"),
    ("привезти", "verb", "to bring (by vehicle)"),
    ("пообещать", "verb", "to promise"),
    ("пройти", "verb", "to pass, to go through"),
    ("проехать", "verb", "to drive past"),
    ("поздравить", "verb", "to congratulate"),
    ("прийти", "verb", "to arrive, to come"),
    ("посмотреть", "verb", "to look, to watch"),
    ("вступить", "verb", "to enter; to come into force"),
    ("вернуться", "verb", "to return, to come back"),
    ("вырасти", "verb", "to grow, to increase"),
    ("укрепиться", "verb", "to strengthen, to gain"),
    ("прибавить", "verb", "to add; to gain"),
    ("попытаться", "verb", "to attempt, to try"),
    ("возбудить", "verb", "to initiate; to open (a case)"),
    ("использовать", "verb", "to use"),
    ("зайти", "verb", "to drop by, to enter"),
    ("выполнять", "verb", "to carry out, to fulfill"),
    ("наращивать", "verb", "to build up, to ramp up"),
    ("сохранять", "verb", "to keep, to preserve"),
    ("сохранить", "verb", "to keep, to save"),
    ("сохраниться", "verb", "to be preserved, to remain"),
    ("обойти", "verb", "to bypass, to go around"),
    ("обменяться", "verb", "to exchange"),
    ("противоречить", "verb", "to contradict"),
    ("завершить", "verb", "to complete, to finish"),
    ("завершиться", "verb", "to end, to be completed"),
    ("измениться", "verb", "to change"),
    ("расходиться", "verb", "to diverge, to disperse"),
    ("вставать", "verb", "to get up, to stand up"),
    ("готовить", "verb", "to prepare, to cook"),
    ("садиться", "verb", "to sit down"),
    ("смотреть", "verb", "to look, to watch"),
    ("выходить", "verb", "to go out, to exit"),
    ("волноваться", "verb", "to worry, to be anxious"),
    ("узнать", "verb", "to find out, to recognize"),
    ("проходить", "verb", "to take place; to pass"),
    ("улучшиться", "verb", "to improve"),
    ("пригласить", "verb", "to invite"),
    ("попросить", "verb", "to ask, to request"),
    ("отремонтировать", "verb", "to repair, to renovate"),
    ("разместить", "verb", "to place, to position"),
    ("уделить", "verb", "to devote, to allocate"),
    ("обновить", "verb", "to update, to renew"),
    ("начаться", "verb", "to begin"),
    ("оказаться", "verb", "to turn out, to find oneself"),
    ("суметь", "verb", "to manage to"),
    ("объяснить", "verb", "to explain"),
    ("указывать", "verb", "to point out, to indicate"),
    ("отвечать", "verb", "to answer, to be responsible"),
    ("отслеживать", "verb", "to track, to monitor"),
    ("уменьшить", "verb", "to reduce, to decrease"),
    ("пострадать", "verb", "to suffer, to be affected"),
    # --- participles (decline as adjectives) ---
    ("взятый", "adj", "taken"),
    ("созданный", "adj", "created"),
    ("оставшийся", "adj", "remaining"),
    ("задействованный", "adj", "involved, engaged"),
    ("имевший", "adj", "having had"),
    ("подписанный", "adj", "signed"),
    ("аккредитованный", "adj", "accredited"),
    ("разрушенный", "adj", "destroyed"),
    ("направленный", "adj", "directed, aimed"),
    ("рассчитанный", "adj", "calculated, designed for"),
    ("построенный", "adj", "built"),
    ("несущий", "adj", "bearing, carrying"),
    ("защищённый", "adj", "protected, secure"),
    ("пострадавший", "adj", "affected, injured (party)"),
    ("необоснованный", "adj", "unfounded, unjustified"),
    ("неделимый", "adj", "indivisible"),
    # --- nouns (declension generated) ---
    ("поставка", "noun", "supply, delivery"),
    ("экспортёр", "noun", "exporter"),
    ("обеспокоенность", "noun", "concern, anxiety"),
    ("финансы", "noun", "finances"),
    ("перенаправление", "noun", "redirection, rerouting"),
    ("маркировка", "noun", "labeling, marking"),
    ("недопустимость", "noun", "inadmissibility"),
    ("слаженность", "noun", "coordination, cohesion"),
    ("космодром", "noun", "cosmodrome, launch site"),
    ("грузоподъёмность", "noun", "payload capacity"),
    ("навигация", "noun", "navigation"),
    ("котировка", "noun", "quote, quotation (price)"),
    ("углеводород", "noun", "hydrocarbon"),
    ("приверженность", "noun", "commitment, adherence"),
    ("нераспространение", "noun", "non-proliferation"),
    ("устав", "noun", "charter, statute"),
    ("замедление", "noun", "slowdown"),
    ("смягчение", "noun", "easing, softening"),
    ("заморозка", "noun", "freeze, freezing"),
    ("документооборот", "noun", "document flow"),
    ("портал", "noun", "portal"),
    ("грамотность", "noun", "literacy"),
    ("импортёр", "noun", "importer"),
    ("пароль", "noun", "password"),
    ("злоумышленник", "noun", "malefactor, attacker"),
    ("трейдер", "noun", "trader"),
    ("лепнина", "noun", "stucco molding"),
    ("ледник", "noun", "glacier"),
    ("солёность", "noun", "salinity"),
    ("таяние", "noun", "melting, thawing"),
    ("энергобаланс", "noun", "energy balance"),
    # --- adjectives (declension + comparative generated) ---
    ("тихоокеанский", "adj", "Pacific"),
    ("беспрепятственный", "adj", "unimpeded, unobstructed"),
    ("межвидовой", "adj", "interspecies"),
    ("нефтегазовый", "adj", "oil-and-gas"),
    ("пропускной", "adj", "throughput, checkpoint (attr.)"),
    ("инфраструктурный", "adj", "infrastructure (attr.)"),
    ("евразийский", "adj", "Eurasian"),
    ("еженедельный", "adj", "weekly"),
    ("профильный", "adj", "specialized, relevant"),
    ("инфляционный", "adj", "inflationary"),
    ("платёжный", "adj", "payment (attr.)"),
    ("межправительственный", "adj", "intergovernmental"),
    ("высший", "adj", "highest, supreme"),
    ("крупнейший", "adj", "largest, biggest"),
    ("спутниковый", "adj", "satellite (attr.)"),
    ("зерновой", "adj", "grain (attr.)"),
    ("сырьевой", "adj", "raw-material, commodity (attr.)"),
    ("возобновляемый", "adj", "renewable"),
    ("прогулочный", "adj", "recreational, for walking"),
    ("ультразвуковой", "adj", "ultrasound (attr.)"),
    ("телемедицинский", "adj", "telemedicine (attr.)"),
    ("нестабильный", "adj", "unstable"),
    ("судоходный", "adj", "navigable"),
    ("неравный", "adj", "unequal"),
    ("малый", "adj", "small, minor"),
    ("донный", "adj", "bottom (attr.)"),
    ("лучший", "adj", "best, better"),
    # --- adverbs ---
    ("неукоснительно", "adverb", "strictly, rigorously"),
]


def supplement_rows(exclude_lemmas):
    """Return note dicts for lemmas not already present, tagged for the matrix layer."""
    rows = []
    seen = set()
    for lemma, pos, gloss in ENTRIES:
        if lemma in exclude_lemmas or lemma in seen:
            continue
        seen.add(lemma)
        rows.append({
            "russian": lemma,
            "lemma": lemma,
            "translation": gloss,
            "pos": pos,
            "tier": 1,
            "tags": "general curated matrix reader_supplement",
        })
    return rows
